### ISSUE TITLE
long double with MSVC/clang-cl is a double precision floating point number

### ISSUE THREAD

**Issue by isuruf** [flang-compiler/f18#1002]
Code at https://github.com/flang-compiler/f18/blob/master/lib/decimal/binary-to-decimal.cpp#L393-L398 assumes that `long double` is  x86 extended precision format, but it is actually double precision.

**Comment by isuruf** [comment]
I can change the if condition from,
```
#if __x86_64__
```
to
```
#if __x86_64__ && !defined(_MSC_VER)
```
but is that desired? Should this be a CMake check?

**Comment by klausler** [comment]
Sounds good to me if that environment has no support for true 80-bit floating-point.

**Comment by isuruf** [comment]
There isn't any high level support (i.e. long double != 80-bit) although there is hardware support.

**Comment by klausler** [comment]
That entry point is just a convenience for testing and use of this library outside the f18 compiler & runtime contexts, so it's not a big deal if you remove it in environments where it can't work.  Be sure to remove its prototype from the header file, too, please; I think that's in `include/flang/decimal` now after Arm's rearrangement of the source base (but beware, it may also be renamed).
