### ISSUE TITLE
Use llvm::sys::RWMutex in runtime/lock.h

### ISSUE THREAD

**Issue by isuruf** [flang-compiler/f18#1005]
Windows has its own threading API. There's also pthreads-win32 project which is a wrapper for windows threads providing the pthreads API, but that library is LGPL.

**Comment by isuruf** [comment]
llvm::sys::RWMutex provides a lock that supports windows too.

**Comment by klausler** [comment]
Are you sure that that routine can be used in a Fortran runtime library without introducing a binary link-time dependence of Fortran applications on llvm libraries?

**Comment by isuruf** [comment]
I can copy the code. Btw, does the lock need support for recursive acquisition or not?

**Comment by klausler** [comment]
It does not need to prevent same-thread deadlock, at least not as I currently understand the requirements of Fortran I/O, but I could be wrong.  This is a work in progress, as you can see.  We'll probably want to have I/O use whatever locking facilities are provided by the OpenMP runtime eventually anyway, so feel free to stub out the pthreads mutexes if you like.
