### ISSUE TITLE
CMake Error for drone.ci due to target "ZLIB::ZLIB" not found

### ISSUE THREAD

**Issue by Sameeranjoshi** [flang-compiler/f18#1042]
The drone.ci build fails for commits done to F18
Log:
https://cloud.drone.io/flang-compiler/f18/1176/1/2

**Comment by DavidTruby** [comment]
This also fails for me locally. libLLVMSupport now (correctly) introduces a PUBLIC dependency on the cmake ZLIB targets, since it calls some ZLIB functions.
