### ISSUE TITLE
System Requirements to build F18?

### ISSUE THREAD

**Issue by davis-matthew** [flang-compiler/f18#1049]
What are the basic system requirements expected to build F18? 

I have 10.7 GB RAM and 1.4GB swap on a 64-bit ubuntu virtual machine and running `make` uses up all of my available memory and fails on building fortranevaluate. 

Is this amount of memory usage expected, and if so, about how much more do you think I will need to allocate in order to successfully build?

**Comment by jeanPerier** [comment]
With 10 Gb ram you should be able to build it but should avoid parallel builds (Try explicitly using make -j1).  I do not know which linker you are using, but if you are running into memory exhaustion during link-time, please consider using a different linker such as lld from LLVM or GNU gold.

**Comment by davis-matthew** [comment]
Thanks for the help. I am no longer encountering the memory issue.

However, my build is still unsuccessful due to some problem with llvm. Is this potentially a version compatibility issue?

> [  2%] Built target FortranCommon
[ 16%] Built target FortranParser
[ 18%] Built target FortranDecimal
[ 33%] Built target FortranEvaluate
[ 34%] Built target FortranLower
Scanning dependencies of target FortranSemantics
[ 34%] Building CXX object lib/Semantics/CMakeFiles/FortranSemantics.dir/mod-file.cpp.o
/home/dataracego/Flang/f18/lib/Semantics/mod-file.cpp: In destructor ‘Fortran::semantics::Temp::~Temp()’:
/home/dataracego/Flang/f18/lib/Semantics/mod-file.cpp:624:22: error: ‘file_t’ is not a member of ‘llvm::sys::fs’
       llvm::sys::fs::file_t native{llvm::sys::fs::convertFDToNativeFile(fd)};
                      ^~~~~~
/home/dataracego/Flang/f18/lib/Semantics/mod-file.cpp:624:22: note: suggested alternative: ‘file_type’
       llvm::sys::fs::file_t native{llvm::sys::fs::convertFDToNativeFile(fd)};
                      ^~~~~~
                      file_type
/home/dataracego/Flang/f18/lib/Semantics/mod-file.cpp:625:22: error: ‘closeFile’ is not a member of ‘llvm::sys::fs’
       llvm::sys::fs::closeFile(native);
                      ^~~~~~~~~
/home/dataracego/Flang/f18/lib/Semantics/mod-file.cpp:625:32: error: ‘native’ was not declared in this scope
       llvm::sys::fs::closeFile(native);
                                ^~~~~~
/home/dataracego/Flang/f18/lib/Semantics/mod-file.cpp:625:32: note: suggested alternative:
In file included from /usr/local/include/llvm/Support/MD5.h:33:0,
                 from /usr/local/include/llvm/Support/FileSystem.h:37,
                 from /home/dataracego/Flang/f18/lib/Semantics/mod-file.cpp:18:
/usr/local/include/llvm/Support/Endian.h:30:31: note:   ‘native’
 enum endianness {big, little, native};
                               ^~~~~~
lib/Semantics/CMakeFiles/FortranSemantics.dir/build.make:566: recipe for target 'lib/Semantics/CMakeFiles/FortranSemantics.dir/mod-file.cpp.o' failed
make[2]: *** [lib/Semantics/CMakeFiles/FortranSemantics.dir/mod-file.cpp.o] Error 1
CMakeFiles/Makefile2:448: recipe for target 'lib/Semantics/CMakeFiles/FortranSemantics.dir/all' failed
make[1]: *** [lib/Semantics/CMakeFiles/FortranSemantics.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tskeith** [comment]
You may be using a version of LLVM that is too old. You should use the latest on the `f18` branch.

`llvm::sys::fs::file_t` is defined in `llvm/Support/FileSystem.h`.

**Comment by davis-matthew** [comment]
I have now produced a build script for review in order to make sure I am doing the steps properly (assume $FLANG_HOME is the PWD where f18 is being installed)

> git clone https://github.com/flang-compiler/f18.git
cd f18
###########################
##LLVM####################
###########################
git clone --depth=1 -b f18 https://github.com/flang-compiler/f18-llvm-project.git
cd f18-llvm-project
mkdir build && cd build
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_INSTALL_UTILS=On -DLLVM_BUILD_TESTS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_ENABLE_ASSERTIONS=OFF  ../llvm
make -j10
sudo make install
###########################
##F18######################
###########################
cd $FLANG_HOME/f18
mkdir build && cd build
cmake -G "Unix Makefiles" -DLLVM_DIR=$FLANG_HOME/f18/f18-llvm-project/build/lib/cmake/llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_TESTS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_ENABLE_ASSERTIONS=OFF  ../
make -j1
sudo make install

This script failed on the cmake for f18 itself with the following message:

> -- Found LLVM 11.0.0git in /home/dataracego/Flang/f18/f18-llvm-project/build/lib/cmake/llvm
-- Linker detection: unknown
CMake Error at CMakeLists.txt:92 (include):
  include could not find load file:

    AddMLIR


> -- Linking driver with FIR and LLVM
-- LLVM libraries: LLVMSupport
-- FLANG version: 0.1.0
CMake Error at include/flang/Optimizer/Dialect/CMakeLists.txt:5 (mlir_tablegen):
  Unknown CMake command "mlir_tablegen".

Do I have a mistake in my script on including/building the mlir component of my llvm?

**Comment by tskeith** [comment]
> -DLLVM_DIR=$FLANG_HOME/f18/f18-llvm-project/build/lib/cmake/llvm

You need to point LLVM_DIR at your install directory, not build. For some reason that is the way to find mlir.

But llvm-lit isn't installed, so you also need to point -DLLVM_EXTERNAL_LIT at llvm-lit in the build directory to be able to run tests.

**Comment by davis-matthew** [comment]
Thank you, I am now able to build f18 successfully with those fixes.
