### ISSUE TITLE
Align with LLVM issue handling

### ISSUE THREAD

**Issue by RichBarton-Arm** [flang-compiler/f18#1055]
LLVM uses bugzilla - https://bugs.llvm.org/ for issue tracking. It has been mooted - http://lists.llvm.org/pipermail/llvm-dev/2019-October/136162.html - that LLVM move to github issues. In fact, github issues is open for creating new issues. 

We need to decide what to do about F18 issues. We should align with the LLVM project as much as we can, but we probably have some leeway in the short term to make our own choices.

**Comment by clementval** [comment]
Some LLVM subproject use the GitHub issues so I guess there shouldn't be a problem for f18 to use them as well.

**Comment by kiranchandramohan** [comment]
Github issues in llvm-project is temporarily disabled until the switch from Bugzilla to github (soon?).
http://lists.llvm.org/pipermail/llvm-dev/2020-March/140129.html

**Comment by RichBarton-Arm** [comment]
@DavidTruby set us up on bugzilla - see https://bugs.llvm.org/describecomponents.cgi?product=flang

The LLVM project is still sorting out how to move to github issues but no ETA yet. We will migrate with the rest of the project.
