### ISSUE TITLE
Align with LLVM on project tracking

### ISSUE THREAD

**Issue by RichBarton-Arm** [flang-compiler/f18#1056]
We use the F18 project's GitHub boards for co-ordinating work. LLVM don't currently use this feature. We should encourage them to enable it for us and port our boards over. Otherwise, we should try and standardize with whatever LLVM use instead.

**Comment by DavidTruby** [comment]
I don't know that LLVM has an equivalent to this: Github project boards aren't enabled for llvm and I don't think Phabricator has an equivalent. Perhaps we should ask on llvm-dev if other people are using something else or if Github boards can be turned on on their side?

**Comment by RichBarton-Arm** [comment]
Agree with previous comment from David. LLVM has no central way to track community projects. We are using a shared [google sheet](https://docs.google.com/spreadsheets/d/1FvHPuSkGbl4mQZRAwCIndvQx9dQboffiD-xD0oqxgU0/edit#gid=633708027) and we are also using github projects in the flang-compiler github. This is fine for now, so closing this ticket.

**Comment by banach-space** [comment]
@RichBarton-Arm Just as an FYI, this is used for tracking OpenMP progress in Clang: https://clang.llvm.org/docs/OpenMPSupport.html
