### ISSUE TITLE
Substring are transformed into reference to the whole string

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18#1091]
```
  character(5) :: c = "abcde"
  print *, c(2:3)
end
```
f18 -funparse:
```
 CHARACTER(LEN=5_4) :: c = "abcde"
 PRINT *, c
END PROGRAM
```

If I add `PARAMETER` to `c`, the output becomes` PRINT *, "abcde"` which is also wrong.

**Comment by klausler** [comment]
PR #1093.

**Comment by klausler** [comment]
Should now be fixed; please close when convenient if so.

**Comment by jeanPerier** [comment]
Thanks ! I could test that the fix solved my issue.
