### ISSUE TITLE
backslash escapes

### ISSUE THREAD

**Issue by pjh40** [flang-compiler/f18#124]
I would expect the simple program:
``` fortran
program foo
  print *, '\'
end program foo
```
to compile and print a backslash when executed, which is what happens with no command line options under gfortran and ifort. f18 rejects the program with `error: incomplete character literal` because backslash escapes are enabled by default.  This leads to two questions: 

1.   Should this non-standard behavior be enabled by default?
2.  Is the "sense" of the command line flags to change this correct?  The current behavior is that
     `-Mbackslash` DISABLES backslash escapes, and `-Mnobackslash` ENABLES them.  Doesn't
     seem intuitive to me.
 
As an aside, I'd be happy to generate fixes and pull requests from a fork for little things like this, but I don't know if that fits into your development model or not.

**Comment by klausler** [comment]
PGI Fortran has backslash escapes enabled by default, with the counterintuitively named options you mentioned.  Using the same options and defaults makes it easier for us to test f18 vs. our in-house test suites.  This is a known design option that has yet to be decided -- the current behavior has just been convenient for us.

**Comment by klausler** [comment]
Reopening so that we don't neglect to work this out soon.

**Comment by klausler** [comment]
Discussion of this example has also clarified what we should do with at least one other concern, and has helped us figure out what we think will be a reasonable principle for handling language extensions.

While we want to accept by default common language extensions and legacy features that would otherwise be erroneous programs, we do not want f18 by default to recognize extensions that, if ignored, would have been acceptable.  Such extensions will have to be enabled explicitly or by tweaking the default setting in a fork.

**Comment by pjh40** [comment]
> ...we do not want f18 by default to recognize extensions that, if ignored, would have been acceptable.

I'm not sure I grok the "would have been acceptable" part there.

I had the thought that you may want create option default sets:  something like '-Mpgi' could enable the behaviors, including the option names (eg -Mbackslash/-Mnobackslash), that your customers are used to, but provide a more standards-compliant set of defaults when no options are given.  Someways like the -std= flag on the C++ files.

**Comment by klausler** [comment]
`print *, 'look, a backslash\'`

is a perfectly valid standard Fortran program and we should not break it by default in the base f18 compiler settings.

**Comment by klausler** [comment]
Commit 57e051eafa1088e83c7d1cef565add6903aed20a implements the new policy, and disables (among some other things) backslash escapes in character literals by default.

**Comment by pjh40** [comment]
I haven't tried to debug it yet, but a fresh checkout and build gives:
```sh
$ tools/f18/f18 -funparse ../build_ff/print.f 
tools/f18/f18: could not scan ../build_ff/print.f
../build_ff/print.f:2:15: error: incomplete character literal
        print *,'\'
                ^^^
```

**Comment by klausler** [comment]
I'll look into it; perhaps I misconfigured a default.  I'm sorry I wasted your time here.  Will keep you posted.

**Comment by klausler** [comment]
And now it really works, with backslash escape sequences enabled or disabled.
