### ISSUE TITLE
Potential problem with CookedSource::GetProvenanceRange

### ISSUE THREAD

**Issue by pjh40** [flang-compiler/f18#134]
I had some unexpected behavior from `CookedSource::GetProvenanceRange`, but I don't know if it is doing what **you** expect or not.  I assumed that, given a `CharBlock` identified by the parsers, this would return a `ProvenanceRange` that mapped all of the cooked `CharBlock` characters back to the original input source.  The way it is implemented now, the returned `ProvenanceRange` starts where I would expect, but extends only to the:
1. end of the `provenanceMap_` range that contains it, or  
2. size of the `cookedRange` argument.

Option 1 is unexpected, because it tends to truncate statements that span multiple `provenanceMap_` ranges.  Option 2 is unexpected because the `cookedRange` has had the spaces baked out of it already, so the resultant `ProvenanceRange` may be much smaller than it should be.

Just to express the intended behavior, I reimplemented that function as:
```c++
ProvenanceRange CookedSource::GetProvenanceRange(CharBlock cookedRange) const {
  ProvenanceRange range1{provenanceMap_.Map(cookedRange.begin() - &data_[0])};
  ProvenanceRange range2{provenanceMap_.Map(cookedRange.end() - &data_[0])};
  return {range1.start(), range2.start() - range1.start()};
}
```
which does work the way I expected it to.  Of course, this is doing a lot of unnecessary work forming ranges that we are discarding, but I was just trying to be as clear and concise as possible.

If I'm misinterpreting the intent of this function, would it be possible to add one that acts the way that I described?  Or is it already there and I've missed it?

Thanks again!

**Comment by klausler** [comment]
This seems like a worthwhile improvement, but I'll have to think a bit about the edge case when `cookedRange.end()` is at EOF.

**Comment by pjh40** [comment]
Implemented this way, the range.Suffix(offset) return value in `OffsetToProvenanceMappings::Map` should fail.  But I think if you did it like:
```c++
Provenance pb{provenanceMap_.Find(cookedRange.begin() - &data_[0])};
Provenance pe{provenanceMap_.Find(cookedRange.end() - &data_[0])};
return {pb, pe-pb};
```
where `OffsetToProvenanceMappings::Find(std::size_t at)` is a non-range version of Map, you are just going to do a bit of pointer arith. and be fine.

**Comment by klausler** [comment]
I think that `Suffix` will be fine, it can return an empty range.

I have a PR out for review that only does a second range mapping if the first provenance range doesn't comprise the entire interval.

**Comment by pjh40** [comment]
How can you decide that or not without looking at the Provenance of the last character of cookedRange.end() is?

**Comment by pjh40** [comment]
BTW: My driver for this stuff is that I'm basically implementing 'flang-format' as a demo to see if I've got the machinery that I need for doing my day job, which is application-specific source-to-source translation that preserves the original input as much as possible (aids in running the code in a debugger).  I know that manipulating the input program text really isn't a main stream concern for you, but something like flang-format may be a nice demonstration of a tool ecosystem built up around your primary tools.

**Comment by klausler** [comment]
The `OffsetToProvenanceMappings` utility class manages mappings from the cooked character stream to the provenance space that are chunked up into contiguous blocks (`ContiguousProvenanceMapping`) that are contiguous in both the cooked character stream and in the provenances.  So any cooked character stream range that is wholly contained by one of these blocks will be contiguous in the provenances as well.

**Comment by pjh40** [comment]
oh, I see: the jumps in the provenances are indicated by a new `ContiguousProvenanceMapping`:

> offsets [57..62] -> provenances [47..52] (6 bytes)
> offsets [63..74] -> provenances [120..131] (12 bytes)

So really, you don't necessarily have to do a second search, you could just need to "increment" through the offset blocks until you reach the cookedRange.end() value.

**Comment by klausler** [comment]
Well, up to `end()-1`.  But there's no API for iterating through the mappings, and we don't really need one so long as the lookup function is fast enough -- and it's obviously only O(log2(#mappings)) which should be fast enough even if confronted with gigabyte-scale sources and only tiny tokens.

**Comment by pjh40** [comment]
Sure, and you could always do the second binary search (std::upper_bound instead?) in [provenanceMap_.begin()+low, provenanceMap_.end()) if you wanted to shave off a hop or two.

**Comment by klausler** [comment]
Change merged; please close this issue if you think that it's resolved.  Thanks for filing the bug report.

**Comment by pjh40** [comment]
Looks good to me.  Thanks for the speedy fix!  BTW, it looks like you merged it onto pmk0...
