### ISSUE TITLE
Syntax error with simple INTERFACE block

### ISSUE THREAD

**Issue by janusw** [flang-compiler/f18#138]
Trying `f18` on this simple test case

```
module m
  implicit none
  interface ifc
     module procedure mp
  end interface
contains
  subroutine mp
  end subroutine
end module
```

yields:

```
PGF90-S-0034-Syntax error at or near :: (/tmp/f18-d7d.f90: 4)
  0 inform,   0 warnings,   1 severes, 0 fatal for m
```

Several issues here:
1) The most obvious one: f18 throws a syntax error on perfectly valid code.
2) `at or near ::` is funny, because there is no `::` in the whole module.
3) The error does not mention the actual file name, but some cryptic /tmp file. In a parallel build with a gazillion files it can be very hard to see where the error is actually coming from.
4) The line number is off if blank or comment lines are inserted.

**Comment by sscalpone** [comment]
By default, f18 will "unparse" its input and run pgf90 on the result.  That error msg is from pgf90.  That explains the /tmp file as well.  Try f18 -fparse only for now.

**Comment by tskeith** [comment]
You can use `-funparse` to see the "unparsed" Fortran that it would have passed to pgf90.

You can see that the 4th line comes out as: `MODULE PROCEDURE :: mp`

The PGI compiler couldn't handle that syntax before version 18.1.

**Comment by janusw** [comment]
> Try  f18 -fparse-only for now.

So you're saying at this point it makes more sense to report bugs with -fparse-only?

**Comment by sscalpone** [comment]
Yes.
