### ISSUE TITLE
Question: parse tree element provenance

### ISSUE THREAD

**Issue by pjh40** [flang-compiler/f18#139]
Just a question, not an issue.  Is there a mechanism to lookup the CharBlock or ProvenanceRange for any element in the parse tree?  For leaf/terminals this would be the lexeme, and for interior nodes it would be the union of the ranges below.

**Comment by klausler** [comment]
No.  Names in the parse tree *are* CharBlocks, and Fortran statements have source ranges, but those are the only hooks in the parse tree to the source locations at the moment that I recall.  (If there are others, they would be node structs with `source` members.)  There is not a general API for mapping parse tree nodes back to the source provenance (yet).

**Comment by pjh40** [comment]
Thanks.  Is that mapping feature planned for some point?

**Comment by pjh40** [comment]
I just built a version of f18 that does exactly what you suggested, decorating everything.  It was a pretty lightweight change:
```
 lib/parser/format-specification.h | 6 ++++++
 lib/parser/parse-tree.h           | 6 +++---
 lib/parser/type-parsers.h         | 4 ++--
```
I'm going to play around with this for a bit and see how it compares to what I was doing.    It seems that you could decorate just the terminal nodes, and build up any "covers" desired from there.  In fact, it may be useful to have some CLASS_TRAIT that indicates that a node is terminal, so that you could define generic visitors that can get you down to the lexemes.

**Comment by pjh40** [comment]
The biggest problem I've encountered is that the parse tree doesn't have placeholders for each token: `PROGRAM <name> -> <name>`, so there is nowhere to hang the CharBlock for the PROGRAM lexeme.  I'm not sure how to get around this without some significant refactoring of the combinators.  My application involves things like renaming functions and changing argument lists with doing as little damage to the original structure of the code (i.e. comments, capitalization, etc), so I need to see everything as tokens tied back to the original source.

Even though I think your team has done a great job creating a fully-conformant parser, I probably would have voted to drop support for 6.3.3.1-2, run the source through flex and build the parsers on tokens, but I also understand that no one asked me for my opinion ;)

**Comment by klausler** [comment]
Renaming functions in place should be tractable with the extant data structures.  An instance of the function name FOO can be mapped precisely back to range of original source locations that constitute the name.  After confirming that the range is comprised by a single file (i.e., no macro replacement was involved), one could generate an edit that replaces that range in (a copy of) the original source file with the new name.  And by working with a parse tree that has been semantically checked and has had its name resolved, one would be confident that the instances of FOO being replaced were just those that were references to a function named FOO, not an element of a local array of the same name.

For argument lists, if you had precise source provenance for the actual arguments, perhaps you could perform the replacement in a similar fashion as an edit on the original sources, with the replacement text coming from an "unparse" of the rewritten/extended arguments.

Of course, performing edits in place on Fortran source can run afoul of line length limitations and has to have some kind of generation of line continuations, at least in fixed form.  (I don't think that f18 has any line length limit in free form, anyway).
