### ISSUE TITLE
Internal error parsing incomplete module

### ISSUE THREAD

**Issue by tskeith** [flang-compiler/f18#142]
Compiling a source file containing the single line `module m`, I get this:
```
fatal internal error: CHECK(!parseState.anyErrorRecovery() || parseState.messages().AnyFatalError()) failed at lib/parser/parsing.cc(106)
```

**Comment by klausler** [comment]
This bug doesn't show up with a clang-built f18, just the g++-built f18 (which is why I didn't see it).  Should be easy to track down and fix.
