### ISSUE TITLE
Linking failure

### ISSUE THREAD

**Issue by pjh40** [flang-compiler/f18#158]
The Hollerith unparse implementation needs some `static_cast<std::uint64_t>` in order to successfully link on Darwin.  Here is the diff vs revision 902054b
[diff-902054b.diff.txt](https://github.com/flang-compiler/f18/files/2254836/diff-902054b.diff.txt)

**Comment by ibara** [comment]
This diff, applied to the current tip of the master branch, fixes the build on OpenBSD as well (using gcc-8.2.0).

**Comment by equal-l2** [comment]
@pjh40 Will you make a PR for this?

**Comment by pjh40** [comment]
Sorry, been away from the office.  I'll put one in today.

**Comment by pjh40** [comment]
This issue was resolved by PR #205.  Thanks!
