### ISSUE TITLE
Out-of-context Hollerith constant parsing masks proper syntax error reporting

### ISSUE THREAD

**Issue by pjh40** [flang-compiler/f18#159]
The resolution for issue #152 fixes the particular case of Holleriths in a LABEL-DO-STMT, but it doesn't address a more general problem, which is that Hollerith constants are being accepted in contexts outside of where they are expected.  This causes problems with syntax error reporting.  For example, a mangled computed goto statement:
```
      subroutine foo(hin,IOUT)
      integer hin
      iout=0
      goto (100 hin-6
      iout=1
 100  iout=iout+1
      end
```
results in f18 generating an incomplete Hollerith error, rather than a syntax error for a computed goto statement. This is confusing, since Hollerith constants should not be expected in this context. As an example of a (seemingly generous) scope for Hollerith constants,

> GNU Fortran supports Hollerith constants in assignments, function arguments, and DATA and ASSIGN statements.

It seems that we need different productions that introduce a scope where Hollerith constants are allowed so that they don't get misdiagnosed in other contexts.  I don't have a language standard that
describes a grammar with Hollerith constants, but I believe that it can be found in an appendix to the F77 standard.

One final note. If there is a desire at some point to create an option for strict standards compliance (e.g. `-std=f08`), there needs to be ways of allowing/disabling Holleriths in different contexts: as above for F66 or F77 with extensions, FORMAT edit descriptors through F90, none past then.  We find pedantic standards enforcement to be useful for code portability.  I'm guessing that there is already a mechanism in the parsing routines to convert between accept, warn or error depending on runtime flags, but I don't know how to employ it.

**Comment by klausler** [comment]
The error message here about the incomplete Hollerith literal is actually coming from the prescanning phase, which tokenizes source lines in a context-independent way as part of macro recognition and replacement.  The parser, which runs after the prescanner, is sensitive to context and will not misrecognize a Hollerith literal when a label is expected.

**Comment by pjh40** [comment]
Does the prescanner *need* to recognize Holleriths?  For macro expansion, it seems that it should just be doing text substitution, and letting the parser figure out if the final text is valid or not.

**Comment by klausler** [comment]
```
#define RIGHT WRONG
10    FORMAT(7H*RIGHT*)
      PRINT 10
```

Macro replacement needs to treat Hollerith literals as if they were strings: don't perform replacement within them, and preserve them when they appear in macro arguments.

**Comment by pjh40** [comment]
Ugh.  I guess you would also need it for case preservation.  Do you need contexts in the preprocessor then?

BTW: gfortran, using cpp, does the RIGHT->WRONG substitution.  Are you using some Hollerith-aware non-cpp preprocessor definition?

**Comment by klausler** [comment]
Yes, we know that gfortran gets this wrong.  The f18 compiler does not try to push Fortran through a C language preprocessor, but instead implements a principled design for Fortran preprocessing that is documented in documentation/preprocessing.md.  The goal is to perform macro recognition and replacement of tokens in an environment that is as independent of Fortran comments and continuation lines as C preprocessing is independent of C comments and removed newlines, and to remove any functional difference between `#include` and `INCLUDE` processing.  We also accept both Fortran and C language expressions in `#if` directives, so that macros meant for use in Fortran source can also be used in conditionals.

**Comment by klausler** [comment]
To respond to your other point: although it would be nice to have the prescanning phase being (more) aware of context when tokenizing for preprocessing, this is a hard thing to improve.  Consider

```
10    FORMAT(X11Hnot allowed)=2
20    FORMAT(X11H)=F(3.14159)
```
Determining whether or not this is a context in which Hollerith is permitted requires knowing whether or not this is a `FORMAT` statement, and that's a hard thing to get precisely right without actually parsing it to completion.  In the cases above, the statement at label 10 is either an assignment or statement function definition, and the one at label 20 really is a `FORMAT` with deceptive text.

So what f18 does is be aware during prescanning/preprocessing of local contexts in which Hollerith recognition should be disabled, and leaves it enabled elsewhere.  This can, as in your case, lead to an error message that you didn't expect.

**Comment by pjh40** [comment]
I guess that this leads to an even more impassioned plea to disable Hollerith support by default.  I'd MUCH rather get error messages that assume common "contemporary" (>=F77) usage than strange messages due to attempts to support antiquated features in complicated ways.  You guys probably have better stats on this than I do, but I can't imagine that code that depends on Hollerith support _in preprocessing_ (or even on the space-agnostic feature of fixed format) makes up the majority of code seen by compilers today.   Certainly, it exists, but is it the case you should be designing for and supporting by default?

**Comment by klausler** [comment]
PR #161 converted the error message from the prescanner about the truncated Hollerith literal into a warning, so that the parser could get a shot at it, and now you can at least see which production(s) got the furthest into that statement before failing.

**Comment by pjh40** [comment]
Ok, still going to be a little confusing, as most of our developers don't know what a Hollerith is, but at least it gets to the mangled computed GOTO.  On the other hand, running `f18 -fparse-only` on the code above, I get
```
goto.f:4:13: possible truncated Hollerith literal
        goto (100 hin-6
              ^^^^^^^^^
goto.f:4:17: error: expected ')'
        goto (100 hin-6
                  ^
goto.f:4:7: in the context: computed GOTO statement
        goto (100 hin-6
        ^
in the context: execution part construct
in the context: execution part
in the context: SUBROUTINE subprogram
goto.f:4:17: error: expected ':'
        goto (100 hin-6
                  ^
goto.f:4:7: in the context: pointer assignment statement
        goto (100 hin-6
        ^
in the context: execution part construct
in the context: execution part
in the context: SUBROUTINE subprogram
tools/f18/f18: could not parse goto.f
```
Is the second message about the pointer assignment context expected?

**Comment by klausler** [comment]
Yes, it is.  When a statement parsing fails entirely, we return the messages from the failed parse that survived the furthest into the statement.  In the case of a tie, I return the messages from both parses that made it the furthest into the mess.

**Comment by klausler** [comment]
Update requested: is there still a bug here to be fixed?
