### ISSUE TITLE
[QUESTION] Why GCC headers

### ISSUE THREAD

**Issue by teamblubee** [flang-compiler/f18#168]
This might be trivial to answer for the core devs but I am curious why use GNU headers for a project targeting LLVM and libc?

What features does glibc provide that are not or cannot be implemented with libc?

**Comment by klausler** [comment]
It is not at all clear what you mean by "GCC headers" and I don't know what usage in the project you're asking about.  We really want to restrict ourselves to C++17 standard library features and LLVM utilities.

**Comment by teamblubee** [comment]
I was referring to the readme for this project says,
"The code has been compiled and tested with clang 6.0 using either GCC 7.3.0 or 8.1.0 headers; however, the headers needed small patches."

It's a bit unclear to me, does this mean that clang6 needs GCC 7.3.0/8.1.0 headers? 

What about clang 7?
