### ISSUE TITLE
Confusing parser error for missing POINTER attribute

### ISSUE THREAD

**Issue by tskeith** [flang-compiler/f18#174]
Compiling this example, the parser emits a bunch of errors because there is no comma after `procedure()` and the POINTER attribute is required.
```
type t
  procedure() :: p
end type
end
```

PGI is more helpful. It says: "PROCEDURE component must have the POINTER attribute - p".

**Comment by klausler** [comment]
Fixed, I believe, with PR#176.  Please confirm and close whenever convenient.  Thanks!
