### ISSUE TITLE
CMake could not find ClangTargets.cmake

### ISSUE THREAD

**Issue by rouson** [flang-compiler/f18#190]
The "[LLVM and clang Dependency](
https://github.com/flang-compiler/f18/blob/master/README.md#llvm-and-clang-dependency)" section of the f18 README.md file provides a link to directions for building clang and LLVM from source. Does building f18 require building clang and LLVM from source?   I tried building clang and llvm using package management on Ubuntu 18.04:
```
sudo apt install clang llvm
```
but I'm not sure how to set `Clang_DIR`.  I tried following:
```
$ export Clang_DIR=/usr/share/llvm-6.0/cmake/
$ git clone https://github.com/flang-compiler/f18
Cloning into 'f18'...
remote: Counting objects: 6799, done.
remote: Compressing objects: 100% (186/186), done.
remote: Total 6799 (delta 236), reused 292 (delta 189), pack-reused 6424
Receiving objects: 100% (6799/6799), 2.47 MiB | 13.55 MiB/s, done.
Resolving deltas: 100% (4839/4839), done.
$ mkdir -p f18/build
$ cd f18/build
$ cmake ..
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build Type: Debug
CMake Error at /usr/share/llvm-6.0/cmake/ClangConfig.cmake:18 (include):
  include could not find load file:

    /usr/lib/cmake/clang/ClangTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:42 (find_package)


-- Found Clang in /usr
-- Found LLVM 6.0.0
-- Using LLVMConfig.cmake in: /usr/lib/llvm-6.0/cmake
-- FLANG version: 0.1.0
-- Configuring incomplete, errors occurred!
See also "/home/rouson/Desktop/f18/build/CMakeFiles/CMakeOutput.log".

```
The [CMakeOutput.log](https://github.com/flang-compiler/f18/files/2399096/CMakeOutput.log) is attached.  I'm not sure whey `cmake` is looking in `/usr/lib/cmake/clang/` (which does not exist) to find `ClangTargets.cmake`, which is actually in the path defined in `$Clang_DIR`.

I also tried building clang and llvm from source using the directions provided at the [link](https://clang.llvm.org/get_started.html) in the same section of the f18 README.md.  Steps 1 to 6 of 10 worked, but the `make` in step 7 fails due to numerous undefined symbols.

**Comment by rouson** [comment]
*ping*

**Comment by sscalpone** [comment]
Hi Damian, I reproduced your issue :)    I don't have a _good_ solution; and somewhat depressingly saw that others on Ubuntu have similar problems using clang/llvm libraries independent of flang.

Right now, f18 doesn't use anything form clang/llvm, so you can get around this issue by commenting out the parts of the top-level CMakefile that deal with finding and linking with clang/llvm libraries.  Or I suppose you can install clang and llvm yourself following the directions at llvm.org.

**Comment by rouson** [comment]
@sscalpone Thanks for the suggestion.  I'll look into building clang/llvm from source, but I also like your suggestion of circumventing clag/llvm if they aren't used.  Doing so gives me the following error message:
```
[ 77%] Linking CXX executable reshape-test
/usr/bin/ld: cannot find -lclangBasic
collect2: error: ld returned 1 exit status
test/evaluate/CMakeFiles/reshape-test.dir/build.make:100: recipe for target 'test/evaluate/reshape-test' failed
make[2]: *** [test/evaluate/reshape-test] Error 1
CMakeFiles/Makefile2:447: recipe for target 'test/evaluate/CMakeFiles/reshape-test.dir/all' failed
make[1]: *** [test/evaluate/CMakeFiles/reshape-test.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```
The changes I made to the top-level `CMakeLists.txt` are described in the following `git diff`:
```
rouson@sourcery-VirtualBox:~/Builds/f18/build$ git diff ../CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a59a3f3..d5b4bd6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -39,11 +39,11 @@ endif()
 
 message(STATUS "Build Type: ${CMAKE_BUILD_TYPE}" )
 
-find_package(Clang REQUIRED CONFIG)
-include_directories(${CLANG_INSTALL_PREFIX/include})
-message(STATUS "Found Clang in ${CLANG_INSTALL_PREFIX}")
-message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
-message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")
+#find_package(Clang REQUIRED CONFIG)
+#include_directories(${CLANG_INSTALL_PREFIX/include})
+#message(STATUS "Found Clang in ${CLANG_INSTALL_PREFIX}")
+#message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
+#message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")
 
 # Get names for the LLVM libraries
 #
@@ -61,10 +61,10 @@ message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")
 #  https://stackoverflow.com/questions/41924375/llvm-how-to-specify-all-link-libraries-as-input-to-llvm-map-components-to-libna
 #  https://stackoverflow.com/questions/33948633/how-do-i-link-when-building-with-llvm-libraries
 
-include_directories(${LLVM_INCLUDE_DIRS})
-add_definitions(${LLVM_DEFINITIONS})
+#include_directories(${LLVM_INCLUDE_DIRS})
+#add_definitions(${LLVM_DEFINITIONS})
 
-llvm_map_components_to_libnames(LLVM_COMMON_LIBS support target option)
+#llvm_map_components_to_libnames(LLVM_COMMON_LIBS support target option)
 
 if(CMAKE_COMPILER_IS_GNUCXX OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
```
Did I miss something?

**Comment by kasaurov** [comment]
Here is a workaround which works for me on Ubuntu 18.04 and llvv/clang 6.0 installed from packages by 'apt-get install'. 
1) Install all the required llvm/clang 6.0 packages
2) sudo ln -s /usr/lib/llvm-6.0/bin/clang /usr/lib/llvm-6.0/bin/clang-6.0
3) sudo ln -s /usr/share/llvm-6.0/cmake /usr/lib/llvm-6.0/lib/cmake/clang
4) env CXX=g++ Clang_DIR=/usr/lib/llvm-6.0/lib/cmake/clang cmake -DCMAKE_BUILD_TYPE=Debug ../../f18

**Comment by sscalpone** [comment]
Over the last few weeks, f18 started to use llvm components for FIR generation.  The project no longer depends on clang.  The CMakeLists.txt file was revamped to support linking with llvm and building with gcc or clang.  This is all documented in the [Readme.md](Readme.md) file.

**Comment by sscalpone** [comment]
With hope, the instructions in Readme.md will work for linking with llvm.  We recommend that you use the same compiler to build llvm and f18, e.g. gcc 8.1.0 or clang 7.0.

@rouson Please reopen this issue if you encounter these errors again.  @kasaurov Thank you for the workaround.
