### ISSUE TITLE
Compilation failure on macOS

### ISSUE THREAD

**Issue by equal-l2** [flang-compiler/f18#202]
- `Integer::HUGE()` collides with macro `HUGE` in `math.h`
- Requires casting in `UnparseVisitor::Before(const HollerithLiteralConstant &x)` (See #158)

**Comment by ibara** [comment]
The `Integer::HUGE()` issue affects all *BSD systems.

**Comment by equal-l2** [comment]
Is there any way to disable `__BSD_VISIBLE` while using POSIX.1-2008 (required for `strnlen`)?

According to FreeBSD headers,  `HUGE` macro is defined in `math.h` if `__BSD_VISIBLE` macro is defined.
`__BSD_VISIBLE` is defined in `sys/cdefs.h` unless either `_ANSI_SOURCE`, `_C99_SOURCE` or `_C11_SOURCE` is defined. 

On macOS, I can successfully disabled `HUGE` macro with `_POSIX_C_SOURCE`(defined as `200809L`) or `_XOPEN_SOURCE`(defined as `700`).

Or maybe can we solve the problem just with `#undef HUGE`?

**Comment by klausler** [comment]
Does anybody have a clue how the macro HUGE in <math.h> gets exposed to the f18 source, which never includes that file?

**Comment by equal-l2** [comment]
The full error log on macOS:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I../include -Iinclude -I/usr/local/opt/llvm/include -std=c++17 -Wall -pedantic -g -DDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT lib/parser/CMakeFiles/FortranParser.dir/user-state.cc.o -MF lib/parser/CMakeFiles/FortranParser.dir/user-state.cc.o.d -o lib/parser/CMakeFiles/FortranParser.dir/user-state.cc.o -c ../lib/parser/user-state.cc
In file included from ../lib/parser/user-state.cc:17:
In file included from ../lib/parser/grammar.h:28:
In file included from ../lib/parser/stmt-parser.h:21:
In file included from ../lib/parser/token-parsers.h:28:
../lib/parser/../evaluate/integer.h:307:28: error: expected member name or ';' after declaration specifiers
  static constexpr Integer HUGE() { return MASKR(bits - 1); }
  ~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/math.h:730:15: note: expanded from macro 'HUGE'
#define HUGE            MAXFLOAT
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/math.h:701:21: note: expanded from macro 'MAXFLOAT'
#define MAXFLOAT    0x1.fffffep+127f
                    ^
```

**Comment by equal-l2** [comment]
From `c++ -H user-state.cc`:
```
. ./user-state.h
.. /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map
... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table
.... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath
..... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h
...... /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h
```

**Comment by ibara** [comment]
On OpenBSD, I first encounter this building tools/f18/f18.cc (since we/I have moved to samurai, https://github.com/michaelforney/samurai, as our Ninja tool because samurai produces non-random builds) but the search path is effectively the same:
```
. tools/f18/../../lib/parser/parsing.h
.. tools/f18/../../lib/parser/instrumented-parser.h
... tools/f18/../../lib/parser/parse-state.h
.... tools/f18/../../lib/parser/user-state.h
..... /usr/include/c++/v1/set
..... /usr/include/c++/v1/unordered_map
...... /usr/include/c++/v1/__hash_table
....... /usr/include/c++/v1/cmath
........ /usr/include/c++/v1/math.h
......... /usr/include/math.h
```
Note, however, that this is a clang-specific issue! When building with g++-8.2.0, f18 compiles without issue, even though `8g++ -H tools/f18/f18.cc` still shows `/usr/include/math.h` in its includes searching. This is because gcc ignores the system `math.h` and instead simply uses its own version of the header from its own internal search path (and this internal gcc header does not have a `HUGE` macro). Makes me wonder what other includes gcc is silently ignoring/replacing with its own versions.

**Comment by pjh40** [comment]
I have the same problem with `HUGE` on Darwin + llvm 7.0.0 (MacPorts build).

**Comment by pjh40** [comment]
I guess that I would vote for supplying -D_POSIX_C_SOURCE=200809L during configuration, which will avoid other potential conflicts in the future.  However, having a function named `HUGE()` doesn't seem to jive with the f18 C++ Style guide...

**Comment by klausler** [comment]
HUGE is the name of a Fortran intrinsic function.

**Comment by klausler** [comment]
Fixed, I hope, by pull request #209, now in the master branch.  Thanks for your help figuring out this problem.  Please confirm the fix whenever convenient and close this bug report if appropriate.

**Comment by equal-l2** [comment]
It now builds and passes tests successfully on macOS.
Thank you all for the fixes!

**Comment by ibara** [comment]
I'll test on OpenBSD, but I imagine that this will work just fine for us too. Thanks for the fix!

**Comment by klausler** [comment]
I'll go ahead and close this bug report; please re-open it if appropriate.  Thanks!
