### ISSUE TITLE
Conversion of Real from lower to higher precision gives unexpected results

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18#269]
Calling `lib/evaluate/real.h` function `Convert `with an argument from a less precise type gives wrong result.
  
```
template<typename A> static ValueWithRealFlags<Real> Convert(
const A &x, Rounding rounding = defaultRounding) 
```

**Suspected Root Cause:**
line 284: `Fraction fraction{Fraction::ConvertUnsigned(xFraction).value};` should be right shifted by `-bitsLost` so that the MSB of the old value remains the MSB of the new value.

**Code reproducing the issue**
```
  #include "../../lib/evaluate/type.h"
  #include <iostream>
  using namespace Fortran::evaluate::value;
  float x{0.5f};
  auto rx{*reinterpret_cast<Real<Integer<32>, 24>*>(&x)};
  auto ry{Real<Integer<64>, 53>::Convert(rx).value}; //issue here
  auto y{*reinterpret_cast<double*>(&ry)};
  std::cout<<"expected: "<<x<<" result: "<<y<<std::endl; //should be identical
```
Currently, the output for me is `"expected: 0.5 result: 9.31323e-10"`

**Comment by klausler** [comment]
Thanks for the bug report.  If the problem is resolved, please close this bug.

**Comment by jeanPerier** [comment]
Tested ok after PR #272 merge. Thanks
