### ISSUE TITLE
Master broken: Label tests loop

### ISSUE THREAD

**Issue by klausler** [flang-compiler/f18#278]
The tests in `test/semantics/label{01,05,06,07}.[fF]90` cause f18 as built from the current master branch (at least with gcc-8.2.0 on x86) to loop indefinitely.

**Comment by pawosm-arm** [comment]
Ah, you've been faster. After applying this commit: https://github.com/flang-compiler/f18/commit/9952b56af090b307f03202c128f242866d76d1a2 `f18 -funparse-with-symbols` hangs on `test/semantics/label{01,05,06,07}.[fF]90` files.

**Comment by klausler** [comment]
Is this bug fully resolved?  If so, please close it.

**Comment by schweitzpgi** [comment]
I assume that was directed at me, but I didn't open the bug.

**Comment by klausler** [comment]
No, but I wasn't sure whether you wanted to keep it open for further work.  Thank you for closing it.
