### ISSUE TITLE
How to use f18 compiler for fortran?

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/f18#285]
Hello,

I was trying to build and use f18 compiler for Fortran. I have run steps to build llvm-clang and f18 as mentioned on the below URL:
https://github.com/flang-compiler/f18

All the steps mentioned here are successfully executed. But, I am not able to use f18 compiler.
I am trying to compile a Fortran program test.f90 as follows:
f18 test.f90

But it does not work and I get the below error:
f18: command not found...
Please guide.

PS:
I don't have flang installed on my system.

Thanks in anticipation!

**Comment by klausler** [comment]
Perhaps your shell's `$PATH` environment variable does not include `.`.  Try running `./f18`.

**Comment by hcltrajesh** [comment]
Thanks! I set path to "F18_BUILD_DIR/tools/f18/f18".
Now, f18 help is getting displayed, but the compilation is still not working.
The flowing error is generated at the time of compilation:
---------------------
**# f18 test.f90
execvp(pgf90) failed: No such file or directory**
---------------------
Please suggest.
Thanks in anticipation!
