### ISSUE TITLE
Restrictions for exit statement not handled in do concurrent semantic checks

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/f18#288]
Restrictions for exit statement is not handled in do concurrent semantic checks.
C1167 states that an exit statement shall not appear in a "do concurrent" construct if it belongs to that construct or an outer construct.

For e.g : the exit from do concurrent via exit mydoc in the following example should not be allowed. While Flang catches this, F18 does not.
```
subroutine run_par(n)
  mydoc: do concurrent(j=1:n)
  mydo:    do k=1,n
             If (k==5) exit mydoc
             If (j==10) exit mydo
           end do mydo
         end do mydoc
end subroutine
```
I have the following questions,
-> Is the plan to cover this in the semantics for exit statement?
-> Are you currently working on this?
-> Would this be a well-defined work for me or my colleagues to get started with F18?

**Comment by klausler** [comment]
f18 has a semantics pass that enforces the control flow restrictions on DO CONCURRENT already, so this missed case is probably a bug.  I'll assign this to @schweitzpgi initially, and he can answer your questions better than I can.

**Comment by schweitzpgi** [comment]
Hi Kiran,

Yes, it looks like an oversight and C1167 isn't in the `do concurrent` checks yet. Thanks for reporting it.

The ultimate plan is to correctly enforce all of the constraints in the standard.  No one is presently working on this semantics check, as far as I know.  It should be straightforward to add this constraint to the `DoConcurrentLabelEnforce` class.  Please let me know if you'd like to do it or have questions.

**Comment by kiranchandramohan** [comment]
Thanks Peter and Eric for your response. Yes, I would like to do this.

**Comment by kiranchandramohan** [comment]
Fixed by the following commit. Thanks @sscalpone.
https://github.com/flang-compiler/f18/commit/f5f6ed8e983bbaffe078e4b206efe95a975a6c85
