### ISSUE TITLE
Why f18 looks for pgf90?

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/f18#290]
This is in continuation to issue #285 .
When f18 is used to compile a Fortran program to create "a.out", the below message is generated:
The below error is generated:

#f18 test.f90 
execvp(pgf90) failed: No such file or directory

Please help me understand the issue and an appropriate solution to the issue.
I am a new newbie to f18, I don't know why pgf90 (PG Fortran) is invoked by f18.

Thanks in anticipation!

**Comment by tskeith** [comment]
The default behavior for f18 currently is to parse the program, convert the parse tree back to Fortran, and compile the result with pgf90. This is useful for testing the parser.

You can run `f18 -help` to see options that affect this behavior. In particular, `-fparse-only` disables the compilation with another compiler. `-fdebug-semantics` enables the currently implemented semantics checks. There are options for dumping some data structures.

**Comment by ramos** [comment]
Hi,

The same problem with f18 installed from FreeBSD ports. Is there any way to actually compile and produce an executable with f18?

Thanks!

**Comment by sscalpone** [comment]
No, f18 cannot produce an executable by itself yet.  It is able to parse and analyze Fortran.   It uses pgf90 (by default) to analyze its results.  This behavior is temporary until f18 can generate llvm ir, etc.

**Comment by dmcdougall** [comment]
You can tell `f18` to look for a different compiler by setting the `F18_FC` environment variable to, say, `flang` or `gfortran`.  Be aware that not all compilers have exactly the same front-end interface; flags that do the same thing in different compilers may be spelt subtly differently.
