### ISSUE TITLE
Could not find ISO module files.

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/f18#318]
Hello,

The following program fails:

>cat iso.f90
 use,intrinsic :: iso_c_binding
 type,bind(c) :: btype_1
  integer(C_INT) :: i
 end type
end

> f18 -fdebug-semantics iso.f90
iso.f90:1:19: error: Cannot find module file for 'iso_c_binding'
   use,intrinsic :: iso_c_binding
                    ^^^^^^^^^^^^^
iso.f90:1:19: iso_c_binding.mod: No such file or directory
   use,intrinsic :: iso_c_binding
                    ^^^^^^^^^^^^^
iso.f90:3:11: error: Must be a constant value
    integer(C_INT) :: i
            ^^^^^
iso.f90:3:11: error: Must have INTEGER type
    integer(C_INT) :: i
            ^^^^^
f18: semantic errors in iso.f90

As seen from error, iso_c_binding module could not be found. 
Does this module file exists in f18  or does f18 support iso_c_binding?

Thanks in advance !!!

**Comment by klausler** [comment]
f18 will support all the standard modules.  It does not support them yet.

**Comment by sscalpone** [comment]
@hcltrajesh OK to close this issue.  I prefer to close it now instead of waiting until the modules are provided because there are scores of similar issues that we could raise, e.g. lack of i/o support.  I prefer not to use issues for project management.

**Comment by hcltrajesh** [comment]
Thanks @klausler .
