### ISSUE TITLE
Error messages would benefit if more statements had source positions

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18#358]
The action-stmt of an if-stmt does not have a source position.

The forall-assignment-stmt alternatives do not have a source position.

The source position would be useful in semantic processing when, for example, an IF stmt is used as the action statement of an IF stmt because it would be best to put the error carat under the action statement.

Note that in i/o statements, the "unit" in "unit=10" doesn't have a source position.

**Comment by klausler** [comment]
Perhaps the `Statement<>` class template should be split into an `UnlabeledStatement<>` with the source location and then `Statement<>` would inherit from it.  Then `UnlabeledStatement<>` would be used to wrap those few "same-line" action statements.
