### ISSUE TITLE
make install?

### ISSUE THREAD

**Issue by AlexisPerry** [flang-compiler/f18#359]
I was able to successfully build f18, but unable to execute "make install".
```
[aperry]$ cmake -DCMAKE_INSTALL_PREFIX=$INSTALLDIR -DLLVM_DIR=$LLVM_DIR_TOP LLVM=$LLVM_DIR_TOP/lib/cmake/llvm ..
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /projects/opt/centos7/gcc/7.3.0/bin/g++
-- Check for working CXX compiler: /projects/opt/centos7/gcc/7.3.0/bin/g++ -- works
.
.
.
Scanning dependencies of target f18
[ 91%] Building CXX object test/evaluate/CMakeFiles/reshape-test.dir/reshape.cc.o
[ 93%] Building CXX object test/evaluate/CMakeFiles/expression-test.dir/expression.cc.o
[ 93%] Building CXX object test/evaluate/CMakeFiles/intrinsics-test.dir/intrinsics.cc.o
[ 95%] Building CXX object tools/f18/CMakeFiles/f18.dir/f18.cc.o
[ 95%] Building CXX object tools/f18/CMakeFiles/f18.dir/dump.cc.o
[ 96%] Linking CXX executable reshape-test
[ 96%] Built target reshape-test
[ 97%] Linking CXX executable intrinsics-test
[ 98%] Linking CXX executable expression-test
[ 98%] Built target expression-test
[ 98%] Built target intrinsics-test
[100%] Linking CXX executable f18
[100%] Built target f18
[aperry]$ make install
make: *** No rule to make target `install'.  Stop.
```

When I look at the Makefile generated by CMake, there is a preinstall target but no install target. Comparing f18's CMakeLists.txt to LLVM's, the language for actually installing f18 seems to be missing.  I don't really know enough about CMake to fix this on my own, otherwise I would give it a try, but since the f18 Readme specifies how to install in a custom location, it makes sense that there should be a way to install the software.

**Comment by tskeith** [comment]
I think all we need is `install(TARGETS f18 DESTINATION bin)` in `tools/f18/CMakeLists.txt`. Then `make install` will copy f18 to the bin subdirectory of $INSTALLDIR.

When it's built with shared libraries it would be a lot more complicated.
