### ISSUE TITLE
F18 DSHIFTR implementation swaps I and J arguments compare to the Standard

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18#363]
DSHIFTR(1, 16, 3) currently returns 0 when it should return 2**29 + 2 according to Fortran 18 Standard section 16.9.66.

It seems the implementation of DSHIFTR on F18 integer scalar type swaps I and J.
Section 16.9.66 defines DSHIFTR as:
`IOR (SHIFTL (I, BIT_SIZE (I)−SHIFT), SHIFTR (J, SHIFT)).`

In `lib/evaluate/integer.h`, the implementation of `constexpr Integer Integer::DSHIFTR(const Integer &fill, int count)`
is `SHIFTR(count).IOR(fill.SHIFTL(bits - count))`.
Considering `*this` maps to `I` and `fill` to `J`, it look like it is reversed.

If modified as suggested, `Real<W, P, IM>::Multiply(const Real &y, Rounding rounding)`, that uses DHSIFTR, should be modified to continue giving a correct result.

**Comment by klausler** [comment]
The mapping of the I & J arguments to `*this` and the `fill` value is probably what needs to be adjusted, along with some comments and maybe the name of the member function.  An integer shift with fill should have `*this` be the value.
