### ISSUE TITLE
Internal Error when using structure constructor

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/f18#376]
The following Internal Error is observed when using a structure constructor in an internal subroutine. The error vanishes if the subroutine is inlined.
```
f18 up_test.f90 -fdebug-semantics

fatal internal error: CHECK(type != nullptr) failed at /home/kircha02/f18/lib/semantics/expression.cc(1791)
Aborted
```
Testcase
```
Program mn
  Type counter
    integer :: val = 10
  End Type
  call s()
Contains
  Subroutine s
    Type(counter) :: c
    c = counter()
    print *, c%val
  End Subroutine
End Program
```

**Comment by klausler** [comment]
The semantic analysis of structure constructors is under active development when I am able to give attention to them.  Do not expect structure constructor semantic analysis to work correctly today.  Depending on the rate of new distractions, I hope to get back to them this week.

**Comment by sscalpone** [comment]
Hi @kiranchandramohan ; thanks for the test case.  Right now, buts are best limited to those dealing with parsing and unparsing.  Stay tuned for when other parts of the compiler are ready for bug reports.

**Comment by klausler** [comment]
Actually, I can pretty easily extract a fix from work in progress; will do.

**Comment by kiranchandramohan** [comment]
Thanks @klausler for fixing this quickly.
@sscalpone I will await further info before filing bugs other than parsing and unparsing.
