### ISSUE TITLE
Too much RAM required.

### ISSUE THREAD

**Issue by ChinouneMehdi** [flang-compiler/f18#431]
I can build llvm with 8 parallel threads and clang with 6 parallel threads with my (4c/8t cpu, 8GB RAM) but when it comes to your project f18 I can't even build it with 2 parallel threads. I need approximately 32 GB of RAM to build it.
Why does it need such a huge memory to build?!

**Comment by ChinouneMehdi** [comment]
I am talking about parallel build `make -jN`

**Comment by klausler** [comment]
The f18 parser is composed at compiler build time via C++ template expansion that elaborates and combines parsers for each of the parts of Fortran syntax.  This technique yields a fast and correct parser for Fortran programs, but is memory-intensive to build with current C++ compilers.  We have chosen to prioritize Fortran compilation correctness and performance.

**Comment by ChinouneMehdi** [comment]
The project needs 8GB to be built sequentially in its early days !
I wonder how much RAM will the project need to be built after two years !

**Comment by klausler** [comment]
The f18 parser is complete today for Fortran 2018 and OpenMP 4.5, so I would not expect the grammar to grow until the next revisions of those standards arrive and are implemented.

**Comment by ChinouneMehdi** [comment]
It is getting worse.
I can build LLVM, Clang, GCC, ... in parallel with my machine but not f18?!
...

**Comment by klausler** [comment]
It might be worth checking f18's build time and build memory requirements again in your environment; I've put some time into mitigating these costs.
