### ISSUE TITLE
Semantic error not found by gfortran/pgf90 in test code

### ISSUE THREAD

**Issue by jjimenezg93** [flang-compiler/f18#432]
Hi.

I'm trying to use this F90 code as a test in F18 [(commit](https://github.com/flang-compiler/f18/commit/1165a7c57fac13294e72666da51e5dcf8af9f252) from which I built):
```fortran
PROGRAM test
implicit none

CALL bar(10)

CONTAINS

FUNCTION foo(x) result(ret)
 IMPLICIT NONE
 REAL :: ret
 INTEGER, INTENT( IN ) :: x
 ret = 2.0*x;
END FUNCTION foo

SUBROUTINE bar(n)
 IMPLICIT NONE
 INTEGER, INTENT( IN ) :: n
 INTEGER :: i = 0
 REAL(kind = 8) :: d
 d = foo(n+i)
END SUBROUTINE bar

END PROGRAM test
```

This is what I get:
```
./f18 -fdebug-semantics test.f90                                                                   
test.f90:20:6: error: not a procedure
   d = foo(n+i)
       ^^^
./f18: semantic errors in test.f90
```
I don't understand why it considers this code invalid, neither `GFortran` (**`GNU Fortran (Ubuntu 8.2.0-7ubuntu1) 8.2.0`**) nor `pgf90` (**`pgf90 18.10-1 LLVM 64-bit target on x86-64 Linux -tp haswell`**) complain about it:
```bash
gfortran -Wall test.f90
pgf90 test.f90
```
I've tried to add a call to `foo` before the contains statement, declare return of `foo` with a global variable instead... but nothing worked so far.

Is there a mistake in the Fortran code or is there any problem in F18?

Thanks!

**Comment by klausler** [comment]
Semantic analysis in f18 is under active development and should not be expected to work yet.

**Comment by jjimenezg93** [comment]
Hi @klausler.

Is there a deadline or estimation for semantic analysis to be working properly?

Thank you!

**Comment by sscalpone** [comment]
You can track the progress here:
https://github.com/flang-compiler/f18/projects

We aren't publishing schedules other than to say our goal is to be able to compile and execute serial code for most of Fortran in September.  Serial code meaning not OpenMP or parallelized DO CONCURRENT.

**Comment by jjimenezg93** [comment]
Fine, thank you!
