### ISSUE TITLE
Help retrieving the type of a ComponentDecl

### ISSUE THREAD

**Issue by jjimenezg93** [flang-compiler/f18#447]
Hi,
I keep going with the custom visitor, so here's yet another question :)

Let's say I have a custom visitor (dumper) which overloads Pre() and Post(). I'm ignoring many types of nodes which I consider unimportant, since I'm trying to print an output which is much more similar to the Fortran code itself. I overload `Pre()` and `Post()` and I'm getting provenance + name of a `ComponentDecl` inside a `DerivedTypeDef`.

For example, for this code:

```
TYPE S
 INTEGER a
 INTEGER(KIND=8) b
END TYPE S
```

I print:
```
| | DerivedTypeDef 0x555555e8e0e0 <fortran90.f90:3:6, fortran90.f90:3:6> s
| | | ComponentDecl 0x555555e8de80 <fortran90.f90:4:10, fortran90.f90:4:10> a 'invalid type'
```
Instead of `'invalid type'`, I'd like to put things like `'char'`, `'i32'` or `'u64'`, so I need to know whether it is a `DerivedType` or a Fortran intrinsic type, besides the number of bytes in the second case.

I'd like to print the type **at this point**, so I can't use the `Pre()` overloads for integer types used in `ParseTreeDumper`, which are visited before `ComponentDecl`.

I'm trying to retrieve this information from the `Symbol`, but I don't find a consistent way of achieving this:

```
    const semantics::Symbol* symbol = std::get<0>(x.t).symbol;
    if (symbol) {
      const semantics::EntityDetails* details =
          symbol->detailsIf<semantics::ObjectEntityDetails>();
      if (details) {
        const semantics::DeclTypeSpec* typeSpec = details->type();
        if (typeSpec &&
            typeSpec->category() == semantics::DeclTypeSpec::Numeric) {
          const semantics::KindExpr& kind = typeSpec->numericTypeSpec().kind();
          // ??
        }
      }
    }
```
Following the definition of `KindExpr`:

```
using SubscriptInteger = Type<TypeCategory::Integer, 8>;
...
using SubscriptIntExpr = evaluate::Expr<evaluate::SubscriptInteger>;
...
using KindExpr = SubscriptIntExpr;
```
And `Expr` is a template which unluckily goes way out of my understanding... However, I guess the next step would be to access the variant inside `Expr`. Is this the best approach to print what I mentioned or is there an easier way?

Thanks in advance!

**Comment by klausler** [comment]
There does not seem to be a bug in this bug report.

**Comment by jjimenezg93** [comment]
It is not a bug report, it should be labeled as "question" but I have no permission to do that.

**Comment by klausler** [comment]
Fortran allows the use of arbitrary constant integer expressions for KIND values, so the symbol table uses the common expression representation to hold the kind of a type.  The value of this expression may depend on the values of type parameters, so the expression cannot be assumed to be a simple constant integer in all cases.

That said, you can fold an expression with `Fold()` in `lib/evaluate/fold.h`, and you can extract a constant integer value from an expression (when that's what the expression is) with `ToInt64()` in the same file.

Please do not assume that the KIND values supported for the intrinsic types are also their sizes in bytes in storage on the target architecture.  This may often be the case, but it is not always so.

**Comment by jjimenezg93** [comment]
Okay, I'll try that.

Thank you!

**Comment by jjimenezg93** [comment]
Hi again @klausler .

I've been messing around with `Fold()`, but I can't get it to work. Given the code I posted previously, I can't call the `Fold()` method of `evaluate/fold.h`, since it requires an rvalue reference (`Expr<T> &&`) and uses move semantics, while the kind object I have is a `const semantics::KindExpr&`...

Could you provide a minimal example of how I could use it given a `const parser::ComponentDecl& x`?

Thank you very much!

**Comment by klausler** [comment]
Yes, Fold() uses move semantics so that the fold expression can use the constituents of the original expression in place.  If the original expression to be folded can't be moved, make a copy that can be.

**Comment by jjimenezg93** [comment]
I understand, but I can't:

```
const semantics::KindExpr& kind = typeSpec->numericTypeSpec().kind();
semantics::KindExpr expr(kind);
evaluate::Fold(context_.foldingContext(), expr);
```

```
test.h:306:11: error: no matching function for call to 'Fold'
fold.h:36:30: note: candidate function [with T = Fortran::evaluate::Type<Fortran::common::TypeCategory::Integer, 8>] not viable: no known conversion from 'semantics::KindExpr' (aka 'Expr<Type<TypeCategory::Integer, 8> >') to 'Expr<Fortran::evaluate::Type<Fortran::common::TypeCategory::Integer, 8> > &&' for 2nd argument
fold.h:41:24: note: candidate template ignored: could not match 'optional' against 'Expr'
```

Is there any place in the project where something similar is already done??

Thanks.

**Comment by klausler** [comment]
You are not passing an rvalue.  Use `std::move()` or construct the copy inline as the argument or use `common::Clone()` or some other technique that produces an rvalue.

**Comment by jjimenezg93** [comment]
I don't know what I was thinking, you're right.

Thanks.
