### ISSUE TITLE
Add guidance to the C++17 style guide about features to avoid

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18#495]
The existing guide does not state that we want to place any restrictions on use of C++17 features.  If, in fact, we **do** want to limit usage, we should say so.

**Comment by klausler** [comment]
The LLVM and other style guides that we reference definitely forbid usage of some C++ features (viz., RTTI, exceptions, static data with runtime constructors) and recommend avoiding a host of others.  None of these guidelines are specific to C++17.  For features new in C++17, I don't know of any that should be avoided -- we definitely need at least one key C++17 language feature, so it seems weird to avoid using others that have real value in catching bugs at build time, improving readability, &c.

**Comment by psteinfeld** [comment]
Thanks, @klausler .  There was discussion in today's f18 meeting of the necessity of avoiding, C++17 features, and I wanted to the real scoop.
