### ISSUE TITLE
Label missing in unparsed output after semantics

### ISSUE THREAD

**Issue by klausler** [flang-compiler/f18#517]
```
  do 1 i=1,2
    goto 2
1 continue
2 do 3 i=1,2
3 continue
  end
```

loses the label `2` in the unparsed output if semantics is enabled.

**Comment by jeanPerier** [comment]
I highly suspect this has to do with `label-do-stmt` rewriting into `nonlabel-do-stmt`. I will give it a look while I have a PR open on related code.
