### ISSUE TITLE
Build failure on Ubuntu 18.04 gcc 7.4

### ISSUE THREAD

**Issue by peterwaller-arm** [flang-compiler/f18#527]
Similar to https://github.com/flang-compiler/f18/issues/312, f18 build fails on the latest Ubuntu LTS with the default compiler (gcc 7.4.0).

Tested on master as of 620441c03e21ae28aed3864b9581cd6cc1705c65 (25 Jun 2019).

There are a lot of errors. One of them is the same proximate error as #312:

```
/usr/include/c++/7/ext/new_allocator.h:136:4: error: use of deleted function ‘Fortran::parser::DataStmtValue::DataStmtValue(const Fortran::parser::DataStmtValue&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /src/llvm-project/f18/lib/parser/user-state.h:25:0,
                 from /src/llvm-project/f18/lib/parser/parse-state.h:28,
                 from /src/llvm-project/f18/lib/parser/instrumented-parser.h:19,
                 from /src/llvm-project/f18/lib/parser/parsing.h:20,
                 from /src/llvm-project/f18/lib/parser/parsing.cc:15:
/src/llvm-project/f18/lib/parser/parse-tree.h:1420:252: note: declared here
   TUPLE_CLASS_BOILERPLATE(DataStmtValue);
```

# [Click for full build log (make -j1)](https://github.com/flang-compiler/f18/files/3329264/error.log)

# Solution

Through bisection I found my way to edd18355be574122aaa9abf58c15d8c50fb085a1 ("Remove needless braces"). If I revert this commit, master builds. I intend to submit this as a PR shortly.

**Comment by peterwaller-arm** [comment]
After reverting edd1835 I see a lot of test failures with ctest that I don't yet understand, so I've not yet sent the PR.

```
76% tests passed, 44 tests failed out of 186

Total Test time (real) =  43.25 sec

The following tests FAILED:
        136 - symbol01.f90 (Failed)
        137 - symbol02.f90 (Failed)
        138 - symbol03.f90 (Failed)
        139 - symbol04.f90 (Failed)
        140 - symbol05.f90 (Failed)
        141 - symbol06.f90 (Failed)
        142 - symbol07.f90 (Failed)
        143 - symbol08.f90 (Failed)
        144 - symbol09.f90 (Failed)
        145 - symbol10.f90 (Failed)
        146 - symbol11.f90 (Failed)
        147 - symbol12.f90 (Failed)
        148 - kinds01.f90 (Failed)
        149 - kinds03.f90 (Failed)
        150 - procinterface01.f90 (Failed)
        151 - modfile01.f90 (Failed)
        152 - modfile02.f90 (Failed)
        153 - modfile03.f90 (Failed)
        154 - modfile04.f90 (Failed)
        155 - modfile05.f90 (Failed)
        156 - modfile06.f90 (Failed)
        157 - modfile07.f90 (Failed)
        158 - modfile08.f90 (Failed)
        159 - modfile09-*.f90 (Failed)
        160 - modfile10.f90 (Failed)
        161 - modfile11.f90 (Failed)
        162 - modfile12.f90 (Failed)
        163 - modfile13.f90 (Failed)
        164 - modfile14.f90 (Failed)
        165 - modfile15.f90 (Failed)
        166 - modfile16.f90 (Failed)
        167 - modfile17.f90 (Failed)
        168 - modfile18.f90 (Failed)
        169 - modfile19.f90 (Failed)
        170 - modfile20.f90 (Failed)
        171 - modfile21.f90 (Failed)
        172 - modfile22.f90 (Failed)
        173 - modfile23.f90 (Failed)
        174 - modfile24.f90 (Failed)
        175 - modfile25.f90 (Failed)
        176 - modfile26.f90 (Failed)
        177 - modfile27.f90 (Failed)
        178 - modfile28.f90 (Failed)
        179 - modfile29.f90 (Failed)
Errors while running CTest
```

**Comment by klausler** [comment]
Please keep us posted and let me know if I can help.  I build with many versions of gcc, including 7.4.0, without seeing these errors.

**Comment by peterwaller-arm** [comment]
I can reproduce the initial build failure with the following `Dockerfile`, and an otherwise clean checkout of f18. Hopefully this makes the full extent of my configuration clear, and rules out most possible sources system contamination.

```
cd .../f18
rm -rf build # Note: no pre-existing build directory.
# Check out master @ 620441c
cat > Dockerfile
[Paste contents of dockerfile from below and press CTRL-D]
docker build -t f18-tmp .
```

#### Dockerfile

```dockerfile
FROM ubuntu:18.04

RUN apt update \
 && apt install -y \
        build-essential \
        cmake \
        llvm-7-dev

COPY . /src/f18
WORKDIR /src/f18

RUN mkdir build && cd build \
 && cmake -DCMAKE_INSTALL_PREFIX=$PWD/install .. \
 && make -j56 \
 && make test
```

If I revert edd1835, this succeeds, including the tests, so I have submitted #532.

This lead me to also look into why tests were failing on my host. It turned out I had unintentionally exported `$CDPATH` in my profile, a handy interactive shell feature. Unfortunately it causes the `cd` shell builtin to print the directory it is moving to under some circumstances, including non-interactive shells, to my surprise. This meant that the construct `( cd foo && command ) > actual_output` used in many tests had some junk in the output, and all of the tests were failing for this reason. The solution was just to unexport CDPATH in my `.profile`.

**Comment by jeanPerier** [comment]
I could also reproduce the issue with an 18.04 LTS Ubuntu image and virtualbox.
g++ version is: `g++ (Ubuntu 7.4.0-1ubuntu1~18.0.4.1) 7.4.0`.
I confirm #532 fixed the issue.

**Comment by pmccormick** [comment]
Ditto for me -- I can reproduce this.  In my most recent tests gcc 8.X appears to avoid these issues.

**Comment by klausler** [comment]
Please confirm when convenient: is this bug fixed?  If so, please close it.  Thanks for your help!

**Comment by peterwaller-arm** [comment]
It builds for me on master now. Thanks.
