### ISSUE TITLE
structure of module files

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/f18#606]
I've looked at .mod files that f18 creates and although they look more human readable and so much nicer than what flang used to create, there's still impression that gfortran (recent versions) with its s-expressions has it better.
Use of s-expressions gives some frames to the plain-text file structure. Without those frames the whole thing looks like free-format set of lines that require in-depth reading to find out where its entities start and where they end. Contrary to this, even badly formatted (visually) gfortran modules seem to be more obvious to read.

**Comment by klausler** [comment]
f18's module files do not just look like Fortran source files; they actually *are* Fortran source files.

This was a deliberate design choice.  It allows us to parse module files and extract and represent their contents internally with the same symbol table representation used for every other Fortran source file.  Using Fortran makes the module files more likely to remain compatible across different versions of f18 in the future.

I'm sorry that you don't find them as readable as other encodings, but nobody but the compiler should be reading module files anyway.

**Comment by pawosm-arm** [comment]
That's fine, the design choice was indeed sound. Thanks for explanation.

**Comment by tskeith** [comment]
If the lack of indentation makes them harder to read (for a human), you can run them through unparse:
`f18 -funparse - < foo.mod`
