### ISSUE TITLE
No error message for stand-alone CYCLE statement

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18#626]
The following program compiles without error:

```
program c1134
  cycle
end program c1134
```

**Comment by klausler** [comment]
Is `EXIT` also broken?

**Comment by psteinfeld** [comment]
Good catch!  Stand-alone ```EXIT``` is also broken.  Interestingly, pgf90 lumps these two statements together in its error message.

**Comment by psteinfeld** [comment]
Fixed by pull request #686
