### ISSUE TITLE
Crash with `!$OMP TARGET MAP` in check-omp-structure.h(146)

### ISSUE THREAD

**Issue by jjimenezg93** [flang-compiler/f18#704]
Hello.

After updating our version to recent commits (first seen after [f6eec72eead759713287dddc124fea375c4f65db](https://github.com/flang-compiler/f18/commit/f6eec72eead759713287dddc124fea375c4f65db) but still crashing after [0948d3d1919ad30b22da9511204b547b1b56da75](https://github.com/flang-compiler/f18/commit/0948d3d1919ad30b22da9511204b547b1b56da75)) we've observed that code containing a `!$OMP TARGET MAP(...)` produces a crash in f18. Example:

```Fortran
PROGRAM OMP_DO_LOOP
    CALL SIMPLE(4)
CONTAINS
    SUBROUTINE SIMPLE(N)
        INTEGER I, N
        REAL, DIMENSION(N) :: A, B
        !$OMP TARGET MAP(TO: A, B)
        !$OMP PARALLEL DO
            DO I = 2, N
                B(I) = (A(I) + A(I-1)) / 2.0
            END DO
        !$OMP END TARGET
    END SUBROUTINE SIMPLE
END PROGRAM OMP_DO_LOOP
```

```Bash
./f18 -fdebug-semantics -fopenmp ./omp_loop.f90 

fatal internal error: CHECK(!ompContext_.empty()) failed at .../f18/lib/semantics/check-omp-structure.h(146)
Aborted (core dumped)
```

This only happens when **performing semantics**, and after removing the `TARGET` clauses it works fine.

I wonder if that's because `MAP` seems to not be implemented in my current version of pgf90
(`pgf90 19.4-0 LLVM 64-bit target on x86-64 Linux -tp haswell`), as I can see when I execute `-fdebug-dump-parse-tree` instead of `-fdebug-semantics`:
```
PGF90-W-0547-OpenMP feature, MAP, not yet implemented in this version of the compiler.
```

Thanks for your time.

**Comment by DavidTruby** [comment]
I've now implemented semantic checking for map clauses and your example compiles for me, could you check if it works for you now?

**Comment by jjimenezg93** [comment]
Sorry for the late reply.

Indeed, it doesn't crash anymore (I've tested at [1688bef152eca1144c985ec7cf9b352a02465130](https://github.com/flang-compiler/f18/commit/1688bef152eca1144c985ec7cf9b352a02465130), though).

Thanks
