### ISSUE TITLE
Help needed about parsing phase of F18

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/f18#707]
(This is not an issue, its a request for help/guidance.)
Hello,

I am studying the parsing mechanism of F18.
I understand that root of Parse tree is returned after the parsing phase is completed (as shown below).

 parseTree_ = program.Parse(parseState);

I could not understand, if we are storing different symbols in any specific data structure.
For example, for below program:
---------------------------
integer::x=1
end
---------------------------

Do we store the variable x, its data type, its initialized value etc. to any specific data structure?
Please suggest/share valuable guidance.
Thanks in anticipation!

**Comment by tskeith** [comment]
Each name of a Fortran entitiy is represented by a `Symbol` that is stored in a `Scope`. Those are structured as a tree rooted at `globalScope_` in `SemanticsContext`.

The `Symbol`s are created in the function `ResolveNames()`. That happens after parsing, near the beginning of semantic analysis.

**Comment by kiranchandramohan** [comment]
You can use the -fdebug-dump-symbols to see the scopes and symbols.

**Comment by hcltrajesh** [comment]
Thank you very much for replying to my query.
I understand that we can dump symbol information using "-fdebug-dump-symbols".
I am still not able to understand how and where information about symbols, statement kind etc. are stored to a parse tree during parsing phase (Parsing phase generates "syntactically correct parse tree").

To understand this further, I investigated the "DumpTree" function which is called to dump a parse tree. I was able to see how the "parseTree" is traversed (Walked), and information about statement kind, variables, literal constants etc. are displayed (retrieved from variant (u) member "MainProgram" and tuple (t) member "ExecutionPart" etc.).
 
After gathering this information, I tried to find where this information (information as dumped by DumpTree()) is being set during parsing phase. I could see that a number of token recognition objects and "parser combinators" are used to parse the cooked source. But, I could not see where information about the given source program is being set. Please guide me here.
Thanks in anticipation!
Rajesh
