### ISSUE TITLE
Help needed about parsing phase of F18 (#707 additional query)

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/f18#712]
I understand that we can dump symbol information using "-fdebug-dump-symbols".
I am still not able to understand how and where information about symbols, statement kind etc. are stored to a parse tree during parsing phase (Parsing phase generates "syntactically correct parse tree").
To understand this further, I investigated the "DumpTree" function which is called to dump a parse tree. I was able to see how the "parseTree" is traversed (Walked), and information about statement kind, variables, literal constants etc. are displayed (retrieved from variant (u) member "MainProgram" and tuple (t) member "ExecutionPart" etc.).
After gathering this information, I tried to find where this information (information as dumped by DumpTree()) is being set during parsing phase. I could see that a number of token recognition objects and "parser combinators" are used to parse the cooked source. *But, I could not see where information about the given source program is being set.* Please guide me here.
Thanks in anticipation!
Rajesh

**Comment by kiranchandramohan** [comment]
The example you previously provided in #707  has an EntityDecl with Name = 'x'

In lib/parser/basic-parsers.h, there is the following comment.
// construct<T>(a, b, ...) returns a parser that succeeds if all of
// its argument parsers do so in succession, and whose result is an
// instance of T constructed upon the values they returned.

In lib/parser/grammar.h, there is a parser Combinator for EntityDecl which returns an EntityDecl.
```
TYPE_PARSER(construct<EntityDecl>(objectName, maybe(arraySpec),
    maybe(coarraySpec), maybe("*" >> charLength), maybe(initialization)))
```

struct EntityDecl is defined In lib/parser/parse-tree.h. It has a tuple defined as follows, where the first element of the tuple is the Name of the Object.
```
  std::tuple<ObjectName, std::optional<ArraySpec>, std::optional<CoarraySpec>,
      std::optional<CharLength>, std::optional<Initialization>>
      t;
```
If you expand out the preprocessor defines you can see that it has a constructor which fills the tuple.
```
EntityDecl(Ts &&... args) : t(std::move(args)...) {}
```

**Comment by sscalpone** [comment]
@hcltrajesh please discuss on the mailing list flang-dev@lists.llvm.org
