### ISSUE TITLE
`ieee_support_flag` is a function but was defined as a subroutine

### ISSUE THREAD

**Issue by klausler** [flang-compiler/f18#725]
Please check your other new additions, too.

**Comment by kiranchandramohan** [comment]
-> Should the argument X be defined for all kinds?
-> Some of the subroutines in this file are elemental (ieee_get_flag) but are not marked so.

**Comment by klausler** [comment]
Is this bug fixed now?

**Comment by psteinfeld** [comment]
I believe that it was fixed by pull request #730.  If you're happy with that, we can close this issue.
