### ISSUE TITLE
Error parsing unparsed code with .eq. and ==

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18#746]
Note that the unparsed output seems to replace .eq. with ==.  
```
MODULE i
 PRIVATE :: e
 INTERFACE OPERATOR(.eq.)
  MODULE PROCEDURE :: e
 END INTERFACE
 INTERFACE OPERATOR(==)
  MODULE PROCEDURE :: e
 END INTERFACE
contains
 ELEMENTAL LOGICAL FUNCTION e(a, b)
  e = .TRUE.
  RETURN
 END FUNCTION
END MODULE
```
```
% f18 -funparse y.f90
MODULE i
 PRIVATE :: e
 INTERFACE OPERATOR(==)
  MODULE PROCEDURE :: e
 END INTERFACE
 INTERFACE OPERATOR(==)
  MODULE PROCEDURE :: e
 END INTERFACE
CONTAINS
 ELEMENTAL LOGICAL FUNCTION e(a, b)
  e = .TRUE.
  RETURN
 END FUNCTION
END MODULE
```
```
z.f90:7:23: error: Procedure 'e' is already specified in generic 'operator(==)'
    MODULE PROCEDURE :: e
                        ^
```

**Comment by tskeith** [comment]
I think unparse is correct and its version is equivalent to the input.

The bug is that during name resolution we don't recognize `operator(.eq.)` and `operator(==)` as meaning the same thing. We are actually creating distinct symbols for them.

15.4.3.4.2 says (in part):

> Because both forms of each relational operator have the same interpretation (10.1.6.2), extending one form (such as <=) has the effect of defining both forms (<= and .LE.).

**Comment by klausler** [comment]
They come out of the parser as the same value `DefinedOperator::IntrinsicOperator::EQ` (&c.), so name resolution must be extracting the cooked source of the operator in all cases.
