### ISSUE TITLE
Weird COMMON syntax not handled properly

### ISSUE THREAD

**Issue by richardbleikamp** [flang-compiler/f18#765]
From FM302.f (one of the old F77 FCVS test suite tests from NIST)

When the input file has a COMMON statement like:
      COMMON IVCN06/BLK5/RVCND1,LVCND1//IVCN07,IVCN08/BLK6/RVCNE1

The generated /tmp/xxx.f90 file has the re-written line:
 COMMON ivcn06, /blk5/rvcnd1, lvcnd1, ivcn07, ivcn08, /blk6/rvcne1

Note the missing "//" after "lvcnd1".  the "//" specifies UNNAMED COMMON, and when absent, the subsequent variables in the list end up in the wrong common block.
I've attached FM302.f (as a .txt file).
[FM302.txt](https://github.com/flang-compiler/f18/files/3664272/FM302.txt)
.  Just compile and run with flang/gfortran/..., and with f18 to reproduce the problem.

**Comment by klausler** [comment]
I've reopened this bug report for you.

The unparsed output from f18 is now
'''
COMMON //ivcn06, /blk5/rvcnd1, lvcnd1, //ivcn07, ivcn08, /blk6/rvcne1
```

That puts `ivcn06`, `ivcn07`, and `ivcn08` into blank COMMON, yes?

**Comment by richardbleikamp** [comment]
yes.  That looks good.  I'll need to figure out why my compiler isn't generating that, even with your change to unparse.cc.  Are you using -funparse, or examing the generated /tmp/....f95 file, or something else?
thanks, Rich

**Comment by klausler** [comment]
I'm looking at the `-funparse` output.

**Comment by richardbleikamp** [comment]
OOPS, I was picking up an old f18 executable via a shell alias, not the newer executable built by make.  Thanks for the quick fix.
