### ISSUE TITLE
using keywords as part of a variable name, fixed form

### ISSUE THREAD

**Issue by richardbleikamp** [flang-compiler/f18#773]
This is a low priority bug, probably in the scanner or parser for fixed form input:
$ cat funny2.f
----
	program foo
	real a = 3
	write(6,*) "reala is ", real a 
	write(6,*) "a is ", a 
	stop
	end
----
gfortran assigns "3" to the variable named "reala" as is should, but f18 assigns "3" to "a".
-----
~/test$ gfortran funny2.f
~/test$ ./a.out
 reala is    3.00000000    
 a is    4.21369473E+33
------
~/test$ f18 funny2.f 
pgf90 -Mbackslash -c -o funny2.o /tmp/f18-1818a.f90
pgf90 -Mbackslash funny2.o
~/test$ ./a.out
 reala is    8431095.00    
 a is    3.00000000

**Comment by klausler** [comment]
Is the indentation correct in the reported test case (i.e.,  do the source lines begin in column 1 despite being fixed form)?

**Comment by klausler** [comment]
The error is that we shouldn't parse a type declaration statement with an initializer unless it also has the doubled colons (`::`) that prevent ambiguity.
