### ISSUE TITLE
Need a way to determine if a subroutine is an intrinsic

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18#779]
In determining whether a call to ```MOVE_ALLOC()``` is an image control statement, I start with a node of the type ```parser::Call``` to be able to access both the procedure and its arguments.  From there, I can get the node for the ```parser::ProcedureDesignator``` which has the name of the procedure which I can test to see if it's ```MOVE_ALLOC```.  But I also need to determine if this is a call to the intrinsic version or to a user defined subroutine.  
I see that there's a function in the the class ```evaluate::ProcedureDesignator``` called ```GetSpecificIntrinsic()``` that looks useful.  But I don't see a way to get to an object of the type ```evaluate::ProcedureDesignator``` from an object whose type is ```parser::ProcedureDesignator```.

**Comment by klausler** [comment]
Soon, `parser::Call` will contain a `TypedExpr` holding the result of analyzing the call; in the case of a subroutine, that expression will have a `ProcedureRef` at its top level that will contain the procedure designator that you need.
