### ISSUE TITLE
Check CRITICAL constructs for image control statements

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18#793]
Constraint C1118 states that the block of a critical-construct shall not contain an image control statement.

This check can be modeled after a similar check for image control statements appearing in DO CONCURRENT statements.  The code to imitated is in check-do.cc in the "Post()" function for "parser::ExecutableConstruct".

**Comment by kiranchandramohan** [comment]
Checks for critical constructs is in our work list. But we will be able to get to this in 2 weeks. If you are implementing this immediately that is fine. Otherwise can you assign to Arm?

**Comment by psteinfeld** [comment]
Thanks, @kiranchandramohan.  I'm happy for ARM to do this work.  I've assigned it to you.  Let me know if someone else is more appropriate.

**Comment by kiranchandramohan** [comment]
Fixed by the following PR.
https://github.com/flang-compiler/f18/pull/897
