### ISSUE TITLE
execvp(/home/z/llvm-9.0.0/bin/f18/bin) failed: Permission denied

### ISSUE THREAD

**Issue by zglin0** [flang-compiler/f18#797]
this is my shell:
#!/bin/bash
export llvm=/home/z/llvm-9.0.0/bin
export f18=$llvm/f18/bin
export PATH=$llvm:$PATH
export PATH=$f18:$PATH
when i try to using : flang h.f90  ,I get the following error:
execvp(/home/z/llvm-9.0.0/bin/f18/bin) failed: Permission denied

**Comment by Sameeranjoshi** [comment]
> You may already know this, but f18 does not compile on its own yet. Currently, it parses the files, can do semantic checks and a few transformations, and then unparses this into a temporary file that is passed to another Fortran compiler. This allows us to test the parser and semantic parts without having an end-to-end compiler yet.[1]

Produces above mentioned error in my case:
F18_FC=<path to another Fortran compiler>/bin

Works:
F18_FC=<path to another Fortran compiler>/bin/compilername
ex. F18_FC=/home/human/toolchain/bin/flang 

[1]https://mail.google.com/mail/u/0/#inbox/FMfcgxwDrvFlhgTFjCbmVZNtzMszdQKn
Thanks

**Comment by klausler** [comment]
`/bin` is the name of a directory, not the name of a Fortran compiler.
