### ISSUE TITLE
Flang installation went cmake error can anyone help me to fix this?

### ISSUE THREAD

**Issue by ponnamsairam** [flang-compiler/f18#813]
/install/flang/build$ sudo cmake ..
-- Found LLVM_CONFIG as /usr/local/bin/llvm-config
-- Linker detection: GNU ld
-- Building with -fPIC
-- Flang version: 10.0.0
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBPGMATH
    linked by target "flangrti_shared" in directory /install/flang/runtime/flangrti

-- Configuring incomplete, errors occurred!
See also "/install/flang/build/CMakeFiles/CMakeOutput.log".
See also "/install/flang/build/CMakeFiles/CMakeError.log".
OS: Ubuntu 16.0.4

**Comment by jeanPerier** [comment]
I think you may have opened the issue against the wrong `Flang`. From you issue, it looks like to me you are trying to build https://github.com/flang-compiler/flang. f18 is the replacement for it that is still under development.

Before re-opening your issue against the right project, please have a look to the [step-by-step Flang installations instructions](https://github.com/flang-compiler/flang/wiki/Building-Flang) if you haven't already . From strep `5.`, I think libpgmath needs to be built before Flang is.
