### ISSUE TITLE
No error message for PURE subroutine with INTENT(OUT) argument

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18#866]
The attached program doesn't produce any error messages even though it violates constraint C1583
that states:

The specification-part of a pure function subprogram shall specify that all its nonpointer dummy data
objects have the INTENT (IN) or the VALUE attribute.
[pure.f90.txt](https://github.com/flang-compiler/f18/files/3946901/pure.f90.txt)

**Comment by klausler** [comment]
> The specification-part of a pure *function* subprogram shall specify that all its nonpointer dummy data
> objects have the INTENT (IN) or the VALUE attribute.
