### ISSUE TITLE
Uncontrollable integer kind conversion

### ISSUE THREAD

**Issue by jme52** [flang-compiler/f18#913]
It is documented that f18 currently violates the Fortran standards by converting expressions of the integer kind under some circumstances: https://github.com/flang-compiler/f18/blob/4f737d4cf684fe84abaa3b44c70187f1f8b53072/documentation/Extensions.md#L19-L27

The inability of the compiler to conform to the standard is a bug.  This behaviour should be at least controllable through a compiler flag, and it should be disabled by default.

Note that if there isn't a way to force f18 to be standards compliant, code written by its users is unlikely to be portable to other compilers, thus making software more difficult to sustain.  This will discourage programmers to use f18 for development.

**Comment by klausler** [comment]
Use `-Mstandard` to get warnings about nonstandard usage; add `-Werror` to treat these warnings as errors.

**Comment by jme52** [comment]
Thank you for the flag, I probably missed it because I couldn't find it in the documentation (I see now that it is listed in the output of `f18 --help`).  May I suggest that it is at least explicitly mentioned in the introduction of [documentation/Extensions.md](https://github.com/flang-compiler/f18/blob/2c6480a62dfb75884373a4fb8b00eadb2d09adf9/documentation/Extensions.md)?

I still think that the best is to default to standards compliance.  If that's not the case, `-Mstandard`should really issue errors (downgradable to warnings via another flag), not just warnings.  That's what most Fortran compilers do nowadays when specifying a standards-related flag, and what users will expect.

**Comment by klausler** [comment]
We accept as much existing Fortran code as possible by default as a deliberate design choice.  As a new compiler, we want the users' experience of porting code to f18 to be as painless as it can be for both old dusty decks and newer standard-compliant applications.
