### ISSUE TITLE
CHECK fails on call to Fortran::semantics::GetExpr

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18#915]
Here's the Fortran source:
subroutine s1()

  type(*)  :: x
  y = x

end subroutine s1

The compiler generates the following parse tree for the expression "x" in the assignment statement:
| | | Expr -> Designator -> DataRef -> Name = 'x'

I added the following code to the compiler:

void DoChecker::Leave(const parser::Expr &parserExpr) {
    if (const auto *expr{GetExpr(parserExpr)}) {

The call to "GetExpr()" fails in the following CHECK in lib/semantics/tools.h:

struct GetExprHelper {
  const SomeExpr *Get(const parser::Expr::TypedExpr &x) {
    CHECK(x);
    return x && x->v ? &*x->v : nullptr;
  }
I can avoid this problem by testing parserExpr.typedExpr before making the call to GetExpr(), but I'm concerned that there's some other potential problem that I'll be covering over by doing this.

**Comment by klausler** [comment]
This is an error recovery case.  `x` is not a dummy argument, and the right-hand-side expression `x` of the assignment is not a valid expression.  Assumed-type variables must be dummy arguments, and their only valid use in Fortran is as an actual argument.  See C709 and C710.  Expression semantic analysis is allowed to fail when the expression is erroneous.

**Comment by psteinfeld** [comment]
I derived the small test case above from our code for iso_c_binding.f90.  Here's a larger test case derived from that file the produces the same problem:
subroutine s1()
  use __Fortran_builtins, only: &
    c_ptr => __builtin_c_ptr
  type(c_ptr) :: c_loc
  type(*)  :: x
  c_loc = c_ptr(loc(x))
end subroutine s1

**Comment by psteinfeld** [comment]
Sorry, I just realized that this test case is also erroneous.  Here's a smaller test case that I believe is legal that shows the same problem:

module iso_c_binding
  use __Fortran_builtins, only: &
    c_f_pointer => __builtin_c_f_pointer, &
    c_ptr => __builtin_c_ptr
  type(c_ptr), parameter :: c_null_ptr = c_ptr()
 contains
  function c_loc(x)
    type(c_ptr) :: c_loc
    type(*), intent(in) :: x
    c_loc = c_ptr(loc(x))
  end function c_loc
end module iso_c_binding

**Comment by psteinfeld** [comment]
As Tim mentions, when we can be certain that the typedExpr field is set for assumed-type dummies and for erroneous expressions, we can remove the check  for a null typedExpr field in the Leave() function for parser::Expr nodes.  This was added in pull request #918.

**Comment by klausler** [comment]
In the comments of that PR we're discussing the best solution.  The `typedExpr` field will *not* be set for erroneous expressions, though.  It may or may not become set for assumed-type dummy arguments.

**Comment by psteinfeld** [comment]
We perform semantic analysis involving expressions which are erroneous.  Thus if we don't set typedExpr for erroneous expressions, we should change GetExpr to not crash when calling it on an expression for which typedExpr has not been set.

**Comment by tskeith** [comment]
`typedExpr` is set for erroneous expressions. In that case it points to a `GenericExprWrapper` that holds a `std::nullopt`.

**Comment by klausler** [comment]
> `typedExpr` is set for erroneous expressions. In that case it points to a `GenericExprWrapper` that holds a `std::nullopt`.

Ok, thanks.  Maybe that's what should be done for assumed-type dummy arguments.
