### ISSUE TITLE
[Sema] cshift intrinsic good argument rejected

### ISSUE THREAD

**Issue by clementval** [flang-compiler/f18#931]
SHIFT argument of rank 1 is rejected by semantic check for the `cshift` intrinsic. The standard (16.9.58) allows (array rank - 1) or scalar. 
 
```fortran
subroutine sub1()
  real a(10)
  real b(10,10)
  integer c(10)
  a = cshift(a, 1)             ! (ARRAY, SHIFT)
  b = cshift(b, c)             ! (ARRAY, SHIFT) ! ERROR HERE
  b = cshift(b, 1, 2)          ! (ARRAY, SHIFT, DIM)
  b = cshift(b, c, 2)          ! (ARRAY, SHIFT, DIM)
end subroutine sub1
```

```bash
dummy.f90:6:7: error: 'shift=' argument has unacceptable rank 1
    b = cshift(b, c)             ! (ARRAY, SHIFT)
        ^^^^^^^^^^^^
./install/bin/f18: semantic errors in dummy.f90
```

I had a look at the intrinsic table and it seems correctly defined with `dimRemoved`. 

https://github.com/flang-compiler/f18/blob/3ad75d123b666a5081540f2afedbedde930b2518/lib/evaluate/intrinsics.cc#L334-L336

And the comment on `dimRemoved` mentions `scalar, or rank(array)-1`
https://github.com/flang-compiler/f18/blob/3ad75d123b666a5081540f2afedbedde930b2518/lib/evaluate/intrinsics.cc#L177

But the check allows `rank(array)-1` only when there is a `DIM` argument.
https://github.com/flang-compiler/f18/blob/3ad75d123b666a5081540f2afedbedde930b2518/lib/evaluate/intrinsics.cc#L1247-L1254

Should the check be changed to keep only the line 1250? Or should there be a special distinction for this case?

**Comment by klausler** [comment]
I think that your analysis is correct, and would not break other intrinsic functions that use `dimRemoved` on their arguments.  Would you like to submit a pull request, or should I fix it here?

**Comment by clementval** [comment]
@klausler Thanks, that's exactly the fix I wanted to propose. I can close this issue.
