### ISSUE TITLE
parsing variable name that contains special keyword and underscore

### ISSUE THREAD

**Issue by naromero77** [flang-compiler/f18#947]
Hi,

I am on the DOE ECP Flang project and Pat McCormick asked me to test the front-end against ECP codes. This snippet of code is from the PICSAR and Plasma Physics code.

Here is the error I get at the command line:
```
mpif90 -g -O3  -fPIC -I/usr/include -D LIBRARY=1  -D  FFTW=1 -c -o src/particle_pushers/laser_pusher_manager_3d.o src/particle_pushers/laser_pusher_manager_3d.F90
PGF90-S-0087-Non-constant expression where constant expression required (/tmp/f18-76b9.f90: 18)
PGF90-S-0087-Non-constant expression where constant expression required (/tmp/f18-76b9.f90: 18)
PGF90-S-0087-Non-constant expression where constant expression required (/tmp/f18-76b9.f90: 18)
```
The problem occurs with a variable called `real_time` (see laser_pusher_manager_3d.F90).

For some reason, upon the first instance of defining this variable, the `real` part of the name gets blown away (see f18-76b9.f90). If you change the variable name to `foo_time`, the problem goes away.

[picsar_real.tar.gz](https://github.com/flang-compiler/f18/files/4110972/picsar_real.tar.gz)

**Comment by klausler** [comment]
I am not able to reproduce the problem with the current f18 using a pared-down case:

```
SUBROUTINE push_laser_particles
  IMPLICIT NONE
  integer, parameter :: num=4, idp=4
  real(num) :: dt
  integer(idp) :: it, nspecies
  INTEGER(idp) :: ispecies, ix, iy, iz, count
  REAL(num)                       :: tdeb, tend, real_time
#if defined(DEBUG)
  WRITE(0, *) "push_laser_particles: start"
#endif
  real_time = it*dt - dt/2.0_num
  IF (nspecies .EQ. 0_idp) RETURN
end
```

Does this snippet fail in your environment?

**Comment by klausler** [comment]
This bug looks like a duplicate of #773, which I fixed on October 2, 2019 with pull request #775.  Is it possible that you are not using an f18 compiler built from recent sources?

**Comment by naromero77** [comment]
Sorry for the quick delay. Taking at look at this now.

**Comment by naromero77** [comment]
This is was my fault. I used Spack to install f18 git master -- but Spack (I think) it is not smart enough to detect change in the git repo. It used an old local cached copy and just installed from that.

Sorry for wasting your time.

**Comment by klausler** [comment]
No worries.  Thanks much for digging deeper and resolving this problem!
