### ISSUE TITLE
Should I use f18 or flang at this moment?

### ISSUE THREAD

**Issue by cesss** [flang-compiler/f18#975]
Hi,

Reading the flang and f18 docs, it's not clear to me if the advice is to use flang or f18 at this moment. I had the hope of having f18 merged into LLVM 10, so I was waiting for the LLVM 10 final release. However, considering that it wasn't possible to do the merge before such release, what would be the preferred choice as of today: flang or f18?

The use is mostly CFD source code, for thermodynamics research.

**Comment by sscalpone** [comment]
F18 does not support code generation yet.  Flang is still the choice for executing programs.

**Comment by cesss** [comment]
Ok, thanks a lot!!
