### ISSUE TITLE
Align F18 supported build compilers to LLVM's

### ISSUE THREAD

**Issue by RichBarton-Arm** [flang-compiler/f18#986]
In order to become a part of the LLVM project we need to match the supported platforms and build compilers. There are some caveats to this:
 * We require C++17 so the earliest supported compiler(s) may be too old. This has been discussed and is an acceptable situation for now.
 * We don't have confidence enough to claim support on Windows yet. This is covered by https://github.com/flang-compiler/f18/issues/971

Here is what LLVM say about host platform and compiler support:
> LLVM is very demanding of the host C++ compiler, and as such tends to expose bugs in the compiler. We also attempt to follow improvements and developments in the C++ language and library reasonably closely. As such, we require a modern host C++ toolchain, both compiler and standard library, in order to build LLVM.
> 
> LLVM is written using the subset of C++ documented in coding standards. To enforce this language version, we check the most popular host toolchains for specific minimum versions in our build systems:
> 
>     Clang 3.5
>     Apple Clang 6.0
>     GCC 5.1
>     Visual Studio 2017
> 
> Anything older than these toolchains may work, but will require forcing the build system with a special option and is not really a supported host platform. Also note that older versions of these compilers have often crashed or miscompiled LLVM.
> 
> For less widely used host toolchains such as ICC or xlC, be aware that a very recent version may be required to support all of the C++ features used in LLVM.
https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library

Note also that there is a list of caveats for certain combinations of build compiler and standard C++ libraries, so we do have that option if we have particular problems.

To do:
 * Understand which compilers can claim to support
 * Update the Readme statement to match
 * Create work items in https://github.com/orgs/flang-compiler/projects/10 to close the gaps.

**Comment by RichBarton-Arm** [comment]
From the flang community call on 19/02, we need to ensure that we can build F18 with the LLVM 10 RC before submitting to the monorepo.

**Comment by RichBarton-Arm** [comment]
Update in call on 09th March: @sscalpone has tested GCC 7.2+ on Power and x86 with no issues.
Now waiting for #969 to land before continuing on Clang versions.

**Comment by DavidTruby** [comment]
I believe this is done, as reflected on the project board. @RichBarton-Arm can you close this?

**Comment by RichBarton-Arm** [comment]
Agree that this is complete.
