### ISSUE TITLE
RANK(B) with B an assumed-size array is folded to 1. It is wrong and should not be constant folded at all.

### ISSUE THREAD

**Issue by Sameeranjoshi** [flang-compiler/f18#990]
For the following test case

```
 module rotflip_rank
implicit none
contains
        subroutine flipud(B)
        integer, intent(inout) :: B(..)
        integer :: j
             j = INT(0, KIND=MERGE(KIND(0), -1, RANK(B) == 0))
        end subroutine flipud
end module rotflip_rank

program assumed_rank
use rotflip_rank, only: flipud
implicit none
integer :: i, A1(3) = [0,1,2]
call flipud(A1)
end program assumed_rank

```
Gives following error:
`$: error: 'kind=' argument must be a constant scalar integer whose value is a supported kind for the intrinsic result type
             j = INT(0, KIND=MERGE(KIND(0), -1, RANK(B) == 0))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`
`RANK(B) == 0` is evaluating to `FALSE`, which is an issue I guess in expression analysis of `RANK` intrinsic
The message seems to be from lib/evaluate/intrinsics.cpp

**Comment by jeanPerier** [comment]
This is indeed a TODO in RANK folding:
https://github.com/flang-compiler/f18/blob/ae7721e611918631d1e3821dbb60f5ffcd9a69b1/lib/evaluate/fold-integer.cpp#L512

**Comment by kargl** [comment]
Just out of curiosity, what do you expect a compiler to produce for the code in the test case?  AFAICT, the current error message is correct.

**Comment by jeanPerier** [comment]
> Just out of curiosity, what do you expect a compiler to produce for the code in the test case? AFAICT, the current error message is correct.

Yes, the code is not valid Fortran, but the error message is slightly misleading (though still correct). f18 is currently complaining because it thinks the `KIND` value is -1. The actual reason is that `MERGE(KIND(0), -1, RANK(B) == 0)` is not a constant expression (because of 10.1.12 (4) (b) (i)). So the error message here should simply be `Must be a constant value` with `MERGE(KIND(0), -1, RANK(B) == 0)` underlined.

That error message change should happen automatically when the TODO is implemented.

**Comment by jeanPerier** [comment]
@kargl , never mind, my last comment regarding the message is wrong: this message will still be emitted. Anyway, the actual TODO related to this issue is that f18 does not raise issues yet for:
```
subroutine sub(b)
  integer, intent(inout) :: B(..)
  integer, parameter :: i = rank(b)
end subroutine
```
I have changed the title for this todo.

**Comment by Sameeranjoshi** [comment]
Quoting where the above test comes from [link](https://github.com/flang-compiler/f18/pull/895#discussion_r377212295), I tried removing the select rank construct, to simplify the test, but I guess it created an invalid Fortran code..
Will the fix for above issue, solve the issue in the select rank construct as well?

**Comment by jeanPerier** [comment]
> Quoting where the above test comes from [link](https://github.com/flang-compiler/f18/pull/895#discussion_r377212295), I tried removing the select rank construct, to simplify the test, but I guess it created an invalid Fortran code..
> Will the fix for above issue, solve the issue in the select rank construct as well?

OK, that is a different  issue. Most likely, the naive fix of my small case above would not solve your issue inside SELECT RANK that is more complex. It would make sens to fix your issue when implementing the TODO.
